---
name: "dotnetcore"
on:
  push:
    branches:
       - develop
jobs:
   build:
      name: build
      run-on: ubuntu-24.04
      steps:
         - uses: actions/checkout@v4
           uses: actions/setup-dotnet@v4
           with:
           dotnet-version: "9.0.100"
         - name: restore
           run: dotnet restore  src/Presentation/Nop.Web/Nop.Web.csproj
         - name: build
           run: dotnet build  src/Presentation/Nop.Web/Nop.Web.csproj --configuration Debug