using FluentMigrator;
using Nop.Core.Domain.Affiliates;
using Nop.Core.Domain.Blogs;
using Nop.Core.Domain.Catalog;
using Nop.Core.Domain.Common;
using Nop.Core.Domain.Configuration;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Directory;
using Nop.Core.Domain.Discounts;
using Nop.Core.Domain.FilterLevels;
using Nop.Core.Domain.Forums;
using Nop.Core.Domain.Gdpr;
using Nop.Core.Domain.Localization;
using Nop.Core.Domain.Logging;
using Nop.Core.Domain.Media;
using Nop.Core.Domain.Menus;
using Nop.Core.Domain.Messages;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.ScheduleTasks;
using Nop.Core.Domain.Security;
using Nop.Core.Domain.Seo;
using Nop.Core.Domain.Shipping;
using Nop.Core.Domain.Stores;
using Nop.Core.Domain.Tax;
using Nop.Core.Domain.Topics;
using Nop.Core.Domain.Vendors;
using Nop.Data.Extensions;

namespace Nop.Data.Migrations.Installation;

[NopSchemaMigration("2020/01/31 11:24:16:2551771", "Nop.Data base schema", MigrationProcessType.Installation)]
public class SchemaMigration : ForwardOnlyMigration
{
    /// <summary>
    /// Collect the UP migration expressions
    /// <remarks>
    /// We use an explicit table creation order instead of an automatic one
    /// due to problems creating relationships between tables
    /// </remarks>
    /// </summary>
    public override void Up()
    {
        this.CreateTableIfNotExists<AddressAttribute>();
        this.CreateTableIfNotExists<AddressAttributeValue>();
        this.CreateTableIfNotExists<GenericAttribute>();
        this.CreateTableIfNotExists<SearchTerm>();
        this.CreateTableIfNotExists<Country>();
        this.CreateTableIfNotExists<Currency>();
        this.CreateTableIfNotExists<MeasureDimension>();
        this.CreateTableIfNotExists<MeasureWeight>();
        this.CreateTableIfNotExists<StateProvince>();
        this.CreateTableIfNotExists<Address>();
        this.CreateTableIfNotExists<Affiliate>();
        this.CreateTableIfNotExists<Language>();
        this.CreateTableIfNotExists<CustomerAttribute>();
        this.CreateTableIfNotExists<CustomerAttributeValue>();
        this.CreateTableIfNotExists<Customer>();
        this.CreateTableIfNotExists<CustomerPassword>();
        this.CreateTableIfNotExists<CustomerAddressMapping>();
        this.CreateTableIfNotExists<CustomerRole>();
        this.CreateTableIfNotExists<CustomerCustomerRoleMapping>();
        this.CreateTableIfNotExists<ExternalAuthenticationRecord>();
        this.CreateTableIfNotExists<CheckoutAttribute>();
        this.CreateTableIfNotExists<CheckoutAttributeValue>();
        this.CreateTableIfNotExists<ReturnRequestAction>();
        this.CreateTableIfNotExists<ReturnRequest>();
        this.CreateTableIfNotExists<ReturnRequestReason>();
        this.CreateTableIfNotExists<ProductAttribute>();
        this.CreateTableIfNotExists<PredefinedProductAttributeValue>();
        this.CreateTableIfNotExists<ProductTag>();
        this.CreateTableIfNotExists<Product>();
        this.CreateTableIfNotExists<ProductTemplate>();
        this.CreateTableIfNotExists<BackInStockSubscription>();
        this.CreateTableIfNotExists<RelatedProduct>();
        this.CreateTableIfNotExists<FilterLevelValue>();
        this.CreateTableIfNotExists<FilterLevelValueProductMapping>();
        this.CreateTableIfNotExists<ReviewType>();
        this.CreateTableIfNotExists<SpecificationAttributeGroup>();
        this.CreateTableIfNotExists<SpecificationAttribute>();
        this.CreateTableIfNotExists<ProductAttributeCombination>();
        this.CreateTableIfNotExists<ProductAttributeCombinationPicture>();
        this.CreateTableIfNotExists<ProductAttributeMapping>();
        this.CreateTableIfNotExists<ProductAttributeValue>();
        this.CreateTableIfNotExists<ProductAttributeValuePicture>();
        this.CreateTableIfNotExists<Order>();
        this.CreateTableIfNotExists<OrderItem>();
        this.CreateTableIfNotExists<RewardPointsHistory>();
        this.CreateTableIfNotExists<GiftCard>();
        this.CreateTableIfNotExists<GiftCardUsageHistory>();
        this.CreateTableIfNotExists<OrderNote>();
        this.CreateTableIfNotExists<RecurringPayment>();
        this.CreateTableIfNotExists<RecurringPaymentHistory>();
        this.CreateTableIfNotExists<CustomWishlist>();
        this.CreateTableIfNotExists<ShoppingCartItem>();
        this.CreateTableIfNotExists<Store>();
        this.CreateTableIfNotExists<StoreMapping>();
        this.CreateTableIfNotExists<LocaleStringResource>();
        this.CreateTableIfNotExists<LocalizedProperty>();
        this.CreateTableIfNotExists<BlogPost>();
        this.CreateTableIfNotExists<BlogComment>();
        this.CreateTableIfNotExists<Category>();
        this.CreateTableIfNotExists<CategoryTemplate>();
        this.CreateTableIfNotExists<ProductCategory>();
        this.CreateTableIfNotExists<CrossSellProduct>();
        this.CreateTableIfNotExists<Manufacturer>();
        this.CreateTableIfNotExists<ManufacturerTemplate>();
        this.CreateTableIfNotExists<ProductManufacturer>();
        this.CreateTableIfNotExists<ProductProductTagMapping>();
        this.CreateTableIfNotExists<ProductReview>();
        this.CreateTableIfNotExists<ProductReviewHelpfulness>();
        this.CreateTableIfNotExists<ProductReviewReviewTypeMapping>();
        this.CreateTableIfNotExists<SpecificationAttributeOption>();
        this.CreateTableIfNotExists<ProductSpecificationAttribute>();
        this.CreateTableIfNotExists<TierPrice>();
        this.CreateTableIfNotExists<Warehouse>();
        this.CreateTableIfNotExists<DeliveryDate>();
        this.CreateTableIfNotExists<ProductAvailabilityRange>();
        this.CreateTableIfNotExists<Shipment>();
        this.CreateTableIfNotExists<ShipmentItem>();
        this.CreateTableIfNotExists<ShippingMethod>();
        this.CreateTableIfNotExists<ShippingMethodCountryMapping>();
        this.CreateTableIfNotExists<ProductWarehouseInventory>();
        this.CreateTableIfNotExists<StockQuantityHistory>();
        this.CreateTableIfNotExists<Download>();
        this.CreateTableIfNotExists<Picture>();
        this.CreateTableIfNotExists<PictureBinary>();
        this.CreateTableIfNotExists<ProductPicture>();
        this.CreateTableIfNotExists<Video>();
        this.CreateTableIfNotExists<ProductVideo>();
        this.CreateTableIfNotExists<Setting>();
        this.CreateTableIfNotExists<Discount>();
        this.CreateTableIfNotExists<DiscountCategoryMapping>();
        this.CreateTableIfNotExists<DiscountProductMapping>();
        this.CreateTableIfNotExists<DiscountRequirement>();
        this.CreateTableIfNotExists<DiscountUsageHistory>();
        this.CreateTableIfNotExists<DiscountManufacturerMapping>();
        this.CreateTableIfNotExists<PrivateMessage>();
        this.CreateTableIfNotExists<ForumGroup>();
        this.CreateTableIfNotExists<Forum>();
        this.CreateTableIfNotExists<ForumTopic>();
        this.CreateTableIfNotExists<ForumPost>();
        this.CreateTableIfNotExists<ForumPostVote>();
        this.CreateTableIfNotExists<ForumSubscription>();
        this.CreateTableIfNotExists<GdprConsent>();
        this.CreateTableIfNotExists<GdprLog>();
        this.CreateTableIfNotExists<ActivityLogType>();
        this.CreateTableIfNotExists<ActivityLog>();
        this.CreateTableIfNotExists<Log>();
        this.CreateTableIfNotExists<Campaign>();
        this.CreateTableIfNotExists<EmailAccount>();
        this.CreateTableIfNotExists<MessageTemplate>();
        this.CreateTableIfNotExists<NewsLetterSubscriptionType>();
        this.CreateTableIfNotExists<NewsLetterSubscription>();
        this.CreateTableIfNotExists<QueuedEmail>();
        this.CreateTableIfNotExists<AclRecord>();
        this.CreateTableIfNotExists<PermissionRecord>();
        this.CreateTableIfNotExists<PermissionRecordCustomerRoleMapping>();
        this.CreateTableIfNotExists<UrlRecord>();
        this.CreateTableIfNotExists<ScheduleTask>();
        this.CreateTableIfNotExists<TaxCategory>();
        this.CreateTableIfNotExists<TopicTemplate>();
        this.CreateTableIfNotExists<Topic>();
        this.CreateTableIfNotExists<Vendor>();
        this.CreateTableIfNotExists<VendorAttribute>();
        this.CreateTableIfNotExists<VendorAttributeValue>();
        this.CreateTableIfNotExists<VendorNote>();
        this.CreateTableIfNotExists<Menu>();
        this.CreateTableIfNotExists<MenuItem>();
    }
}