<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Copyright>Copyright © Nop Solutions, Ltd</Copyright>
    <Company>Nop Solutions, Ltd</Company>
    <Authors>Nop Solutions, Ltd</Authors>
    <Version>5.00</Version>
    <Description>The project contains a set of core classes for impelementing testing</Description>
    <PackageLicenseUrl>https://www.nopcommerce.com/license</PackageLicenseUrl>
    <PackageProjectUrl>https://www.nopcommerce.com/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/nopSolutions/nopCommerce</RepositoryUrl>
    <RootNamespace>$(MSBuildProjectName.Substring(0, 9).Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Nop.Web.Tests\Public\Factories\ProductModelFactoryForTest.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" Version="9.4.0" />
    <PackageReference Include="FluentMigrator.Runner.SQLite" Version="8.0.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Presentation\Nop.Web\Nop.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Connections.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Connections.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
