using System.Collections.Generic;
using FluentMigrator;
using Nop.Core.Infrastructure;
using Nop.Data;
using Nop.Data.Migrations;
using Nop.Services.Localization;

namespace Nop.Web.Framework.Migrations.UpgradeTo440
{
    [NopMigration("2020-06-10 00:00:00", "4.40.0", UpdateMigrationType.Localization)]
    [SkipMigrationOnInstall]
    public class LocalizationMigration : MigrationBase
    {
        /// <summary>Collect the UP migration expressions</summary>
        public override void Up()
        {
            if (!DataSettingsManager.IsDatabaseInstalled())
                return;

            //do not use DI, because it produces exception on the installation process
            var localizationService = EngineContext.Current.Resolve<ILocalizationService>();

            //use localizationService to add, update and delete localization resources
            localizationService.DeleteLocaleResourcesAsync(new List<string>
            {
                "Account.Fields.VatNumber.Status",
                "Account.Fields.VatNumberStatus",
                "Account.PasswordRecovery.OldPassword",
                "Account.PasswordRecovery.OldPassword.Required",
                "Account.Register.Unsuccessful",
                "Account.ShoppingCart",
                "ActivityLog.AddNewWidget",
                "ActivityLog.DeleteWidget",
                "ActivityLog.EditWidget",
                "Admin.Address.Fields.StateProvince.Required",
                "Admin.Catalog.AdditionalProductReviews.Fields.Description",
                "Admin.Catalog.Categories.Breadcrumb",
                "Admin.Catalog.Categories.Fields.CreatedOn",
                "Admin.Catalog.Categories.SwitchToListView",
                "Admin.Catalog.Manufacturers.Fields.CreatedOn",
                "Admin.Catalog.Products.ProductAttributes.Attributes.ValidationRules.ViewLink",
                "Admin.Catalog.Products.ProductAttributes.Attributes.Values.EditAttributeDetails",
                "Admin.Catalog.Products.SpecificationAttributes.NoAttributeOptions",
                "Admin.Catalog.Products.SpecificationAttributes.SelectOption",
                "Admin.Common.CancelChanges",
                "Admin.Common.Check",
                "Admin.Common.DeleteConfirmationParam",
                "Admin.Common.List",
                "Admin.Common.LoseUnsavedChanges",
                "Admin.Common.SaveChanges",
                "Admin.Configuration.Currencies.Localization",
                "Admin.Configuration.Currencies.Select",
                "Admin.Configuration.EmailAccounts.Fields.SendTestEmailTo.Button",
                "Admin.Configuration.PaymentMethods",
                "Admin.Configuration.PaymentMethodsAndRestrictions",
                "Admin.Configuration.Settings.CustomerUser.BlockTitle.DefaultFields",
                "Admin.Configuration.Settings.CustomerUser.BlockTitle.ExternalAuthentication",
                "Admin.Configuration.Settings.CustomerUser.BlockTitle.TimeZone",
                "Admin.Configuration.Settings.CustomerUser.CustomerSettings",
                "Admin.Configuration.Settings.Order.OrderSettings",
                "Admin.Configuration.Settings.ProductEditor.BlockTitle.LinkedProducts",
                "Admin.Configuration.Settings.ProductEditor.Id",
                "Admin.Configuration.Shipping.Measures.Dimensions.Description",
                "Admin.Configuration.Shipping.Measures.Weights.Description",
                "Admin.Configuration.SMSProviders",
                "Admin.Configuration.SMSProviders.BackToList",
                "Admin.Configuration.SMSProviders.Configure",
                "Admin.Configuration.SMSProviders.Fields.FriendlyName",
                "Admin.Configuration.SMSProviders.Fields.IsActive",
                "Admin.Configuration.SMSProviders.Fields.SystemName",
                "Admin.ContentManagement.Topics.Fields.Store.AllStores",
                "Admin.ContentManagement.Widgets.ChooseZone",
                "Admin.ContentManagement.Widgets.ChooseZone.Hint",
                "Admin.Customers.Customers.Fields.Email.Required",
                "Admin.Customers.Customers.Fields.FirstName.Required",
                "Admin.Customers.Customers.Fields.LastName.Required",
                "Admin.Customers.Customers.Fields.SystemName",
                "Admin.Customers.Customers.Fields.SystemName.Hint",
                "Admin.Customers.Customers.Fields.Username.Required",
                "Admin.Customers.Customers.RewardPoints.Alert.HistoryAdd",
                "Admin.DT.Processing",
                "Admin.NopCommerceNews.HideAdv",
                "Admin.NopCommerceNews.ShowAdv",
                "Admin.Orders.OrderNotes.Alert.Add",
                "Admin.Promotions.Discounts.Fields.AppliedToCategories",
                "Admin.Promotions.Discounts.Fields.AppliedToCategories.Hint",
                "Admin.Promotions.Discounts.Fields.AppliedToCategories.NoRecords",
                "Admin.System.QueuedEmails.Fields.Priority.Required",
                "Common.DeleteConfirmationParam",
                "Common.Extensions.RelativeFormat",
                "Common.Home",
                "EUCookieLaw.CannotBrowse",
                "EUCookieLaw.Title",
                "Filtering.FilterResults",
                "Forum.Replies.Count",
                "Forum.Topics.Count",
                "News.Archive",
                "Newsletter.ResultAlreadyDeactivated",
                "PageTitle.EmailRevalidation",
                "PDFInvoice.CreatedOn",
                "PDFInvoice.Note",
                "PrivateMessages.Send.Subject.Required",
                "PrivateMessages.Sent.DateColumn",
                "PrivateMessages.Sent.DeleteSelected",
                "PrivateMessages.Sent.SubjectColumn",
                "PrivateMessages.Sent.ToColumn",
                "Profile.FullName",
                "RewardPoints.Message.Expired",
                "ShoppingCart.AddToWishlist.Update",
                "ShoppingCart.UpdateCartItem",
                "Tax.SelectType",
                "Admin.Configuration.Settings.GeneralCommon.BlockTitle.FullText",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.CurrenlyDisabled",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.CurrenlyEnabled",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.Disable",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.Disabled",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.Enable",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.Enabled",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.NoiseWords",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.NotSupported",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.SearchMode",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.SearchMode.Hint",
                "Admin.Configuration.Settings.GeneralCommon.FullTextSettings.Supported",
                "Enums.Nop.Core.Domain.Common.FulltextSearchMode.And",
                "Enums.Nop.Core.Domain.Common.FulltextSearchMode.ExactMatch",
                "Enums.Nop.Core.Domain.Common.FulltextSearchMode.Or",
            }).Wait();

            localizationService.AddLocaleResourceAsync(new Dictionary<string, string>
            {
                ["Admin.System.Warnings.PluginNotEnabled.AutoFixAndRestart"] = "Uninstall and delete all not used plugins automatically (site will be restarted)",
                ["Admin.Configuration.AppSettings"] = "App settings",
                ["Admin.Configuration.AppSettings.Cache"] = "Cache configuration",
                ["Admin.Configuration.AppSettings.Cache.DefaultCacheTime"] = "Default cache time",
                ["Admin.Configuration.AppSettings.Cache.DefaultCacheTime.Hint"] = "Set default cache time (in minutes).",
                ["Admin.Configuration.AppSettings.Cache.ShortTermCacheTime"] = "Short term cache time",
                ["Admin.Configuration.AppSettings.Cache.ShortTermCacheTime.Hint"] = "Set short term cache time (in minutes).",
                ["Admin.Configuration.AppSettings.Cache.BundledFilesCacheTime"] = "Bundled files cache time",
                ["Admin.Configuration.AppSettings.Cache.BundledFilesCacheTime.Hint"] = "Set bundled files cache time (in minutes).",
                ["Admin.Configuration.AppSettings.Hosting"] = "Hosting configuration",
                ["Admin.Configuration.AppSettings.Hosting.UseHttpClusterHttps"] = "Use HTTP_CLUSTER_HTTPS",
                ["Admin.Configuration.AppSettings.Hosting.UseHttpClusterHttps.Hint"] = "Enable this setting if your hosting uses a load balancer. It’ll be used to determine whether the current request is HTTPS.",
                ["Admin.Configuration.AppSettings.Hosting.UseHttpXForwardedProto"] = "Use HTTP_X_FORWARDED_PROTO",
                ["Admin.Configuration.AppSettings.Hosting.UseHttpXForwardedProto.Hint"] = "Enable this setting if you use a reverse proxy server (for example, if you host your site on Linux with Nginx/Apache and SSL).",
                ["Admin.Configuration.AppSettings.Hosting.ForwardedHttpHeader"] = "Forwarded HTTP header",
                ["Admin.Configuration.AppSettings.Hosting.ForwardedHttpHeader.Hint"] = "Use this setting if your hosting doesn’t use ’X-FORWARDED-FOR’ header to determine IP address. You can specify a custom HTTP header (e.g. CF-Connecting-IP, X-FORWARDED-PROTO, etc).",
                ["Admin.Configuration.AppSettings.Redis"] = "Redis configuration",
                ["Admin.Configuration.AppSettings.Redis.Enabled"] = "Use Redis",
                ["Admin.Configuration.AppSettings.Redis.Enabled.Hint"] = "Enable this setting to use Redis server.",
                ["Admin.Configuration.AppSettings.Redis.ConnectionString"] = "Connection string",
                ["Admin.Configuration.AppSettings.Redis.ConnectionString.Hint"] = "Specify Redis connection string.",
                ["Admin.Configuration.AppSettings.Redis.DatabaseId"] = "Database ID",
                ["Admin.Configuration.AppSettings.Redis.DatabaseId.Hint"] = "Set the specific Redis database. Leave empty to use the different database for each data type (used by default).",
                ["Admin.Configuration.AppSettings.Redis.UseCaching"] = "Use caching",
                ["Admin.Configuration.AppSettings.Redis.UseCaching.Hint"] = "Enable this setting to use Redis server for caching (instead of default in-memory caching).",
                ["Admin.Configuration.AppSettings.Redis.StoreDataProtectionKeys"] = "Store Data Protection keys",
                ["Admin.Configuration.AppSettings.Redis.StoreDataProtectionKeys.Hint"] = "Enable this setting to store the Data Protection keys in Redis database.",
                ["Admin.Configuration.AppSettings.Redis.StorePluginsInfo"] = "Store plugins info",
                ["Admin.Configuration.AppSettings.Redis.StorePluginsInfo.Hint"] = "Enable this setting to store the plugins info in Redis database (instead of default file in directory).",
                ["Admin.Configuration.AppSettings.Redis.IgnoreTimeoutException"] = "Ignore timeout exception",
                ["Admin.Configuration.AppSettings.Redis.IgnoreTimeoutException.Hint"] = "Enable this setting to ignore timeout exception (this increases cache stability but may slightly decrease site performance).",
                ["Admin.Configuration.AppSettings.AzureBlob"] = "Azure Blob storage configuration",
                ["Admin.Configuration.AppSettings.AzureBlob.ConnectionString"] = "Connection string",
                ["Admin.Configuration.AppSettings.AzureBlob.ConnectionString.Hint"] = "Specify the connection string for Azure Blob storage.",
                ["Admin.Configuration.AppSettings.AzureBlob.ContainerName"] = "Container name",
                ["Admin.Configuration.AppSettings.AzureBlob.ContainerName.Hint"] = "Specify the container name for Azure Blob storage.",
                ["Admin.Configuration.AppSettings.AzureBlob.EndPoint"] = "Endpoint",
                ["Admin.Configuration.AppSettings.AzureBlob.EndPoint.Hint"] = "Specify the endpoint for Azure Blob storage.",
                ["Admin.Configuration.AppSettings.AzureBlob.AppendContainerName"] = "Append container name",
                ["Admin.Configuration.AppSettings.AzureBlob.AppendContainerName.Hint"] = "Enable this setting to append the endpoint with the container name when constructing the URL.",
                ["Admin.Configuration.AppSettings.AzureBlob.StoreDataProtectionKeys"] = "Store Data Protection keys",
                ["Admin.Configuration.AppSettings.AzureBlob.StoreDataProtectionKeys.Hint"] = "Enable this setting to store the Data Protection keys in Azure Blob Storage.",
                ["Admin.Configuration.AppSettings.AzureBlob.DataProtectionKeysContainerName"] = "Container name for Data Protection keys",
                ["Admin.Configuration.AppSettings.AzureBlob.DataProtectionKeysContainerName.Hint"] = "Specify the container name for the Data Protection keys. This should be a private container separate from the Blob container used for media storage.",
                ["Admin.Configuration.AppSettings.AzureBlob.DataProtectionKeysVaultId"] = "Key vault ID",
                ["Admin.Configuration.AppSettings.AzureBlob.DataProtectionKeysVaultId.Hint"] = "Specify the Azure key vault ID used to encrypt the Data Protection keys.",
                ["Admin.Configuration.AppSettings.Installation"] = "Installation configuration",
                ["Admin.Configuration.AppSettings.Installation.DisableSampleData"] = "Disable sample data",
                ["Admin.Configuration.AppSettings.Installation.DisableSampleData.Hint"] = "Enable this setting to disable sample data for installation.",
                ["Admin.Configuration.AppSettings.Installation.DisabledPlugins"] = "Disabled plugins",
                ["Admin.Configuration.AppSettings.Installation.DisabledPlugins.Hint"] = "Specify a list of plugins (comma separated) ignored during installation.",
                ["Admin.Configuration.AppSettings.Plugin"] = "Plugin configuration",
                ["Admin.Configuration.AppSettings.Plugin.ClearPluginShadowDirectoryOnStartup"] = "Clear plugin shadow directory on startup",
                ["Admin.Configuration.AppSettings.Plugin.ClearPluginShadowDirectoryOnStartup.Hint"] = "Enable this setting to clear the plugin shadow directory (/Plugins/bin) on application startup.",
                ["Admin.Configuration.AppSettings.Plugin.CopyLockedPluginAssembilesToSubdirectoriesOnStartup"] = "Copy locked plugins to subdirectories on startup",
                ["Admin.Configuration.AppSettings.Plugin.CopyLockedPluginAssembilesToSubdirectoriesOnStartup.Hint"] = "Enable this setting to copy ’locked’ assemblies from the plugin shadow directory (/Plugins/bin) to temporary subdirectories on application startup.",
                ["Admin.Configuration.AppSettings.Plugin.UseUnsafeLoadAssembly"] = "Use unsafe load assembly",
                ["Admin.Configuration.AppSettings.Plugin.UseUnsafeLoadAssembly.Hint"] = "Enable this setting to load an assembly into the load-from context, bypassing some security checks.",
                ["Admin.Configuration.AppSettings.Plugin.UsePluginsShadowCopy"] = "Use plugins shadow copy",
                ["Admin.Configuration.AppSettings.Plugin.UsePluginsShadowCopy.Hint"] = "Enable this setting to copy plugins to the shadow directory (/Plugins/bin) on application startup.",
                ["Admin.Configuration.AppSettings.Common"] = "Common configuration",
                ["Admin.Configuration.AppSettings.Common.DisplayFullErrorStack"] = "Display full error",
                ["Admin.Configuration.AppSettings.Common.DisplayFullErrorStack.Hint"] = "Enable this setting to display the full error in production environment. It’s ignored (always enabled) in development environment.",
                ["Admin.Configuration.AppSettings.Common.MiniProfilerEnabled"] = "Enable MiniProfiler",
                ["Admin.Configuration.AppSettings.Common.MiniProfilerEnabled.Hint"] = "Enable this setting to display the performance indicator by MiniProfiler. By default, the performance indicator can see only Administrators, to change this behavior set ACL rules in the admin area.",
                ["Admin.Configuration.AppSettings.Common.UserAgentStringsPath"] = "User agent strings path",
                ["Admin.Configuration.AppSettings.Common.UserAgentStringsPath.Hint"] = "Specify a path to the file with user agent strings.",
                ["Admin.Configuration.AppSettings.Common.CrawlerOnlyUserAgentStringsPath"] = "Crawler user agent strings path",
                ["Admin.Configuration.AppSettings.Common.CrawlerOnlyUserAgentStringsPath.Hint"] = "Specify a path to the file with crawler only user agent strings. Leave empty to always use full version of user agent strings file.",
                ["Admin.Configuration.AppSettings.Common.UseSessionStateTempDataProvider"] = "Use session state for TempData",
                ["Admin.Configuration.AppSettings.Common.UseSessionStateTempDataProvider.Hint"] = "Enable this setting to store TempData in the session state. By default the cookie-based TempData provider is used to store TempData in cookies.",
                ["ActivityLog.AddNewSpecAttributeGroup"] = "Added a new specification attribute group (’{0}’)",
                ["ActivityLog.EditSpecAttributeGroup"] = "Edited a specification attribute group (’{0}’)",
                ["ActivityLog.DeleteSpecAttributeGroup"] = "Deleted a specification attribute group (’{0}’)",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Buttons.AddNew"] = "Add attribute",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Buttons.DeleteSelected"] = "Delete attributes (selected)",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Fields.SpecificationAttributeGroup"] = "Group",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Fields.SpecificationAttributeGroup.Hint"] = "The group of the specification attribute.",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Fields.SpecificationAttributeGroup.None"] = "None",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Added"] = "The new attribute group has been added successfully.",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.AddNew"] = "Add a new specification attribute group",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.BackToList"] = "back to specification attribute list",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Buttons.AddNew"] = "Add group",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.DefaultGroupName"] = "Default group (non-grouped specification attributes)",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Deleted"] = "The attribute group has been deleted successfully.",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.EditAttributeGroupDetails"] = "Edit specification attribute group details",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Fields.DisplayOrder"] = "Display order",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Fields.DisplayOrder.Hint"] = "The display order of the specification attribute group.",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Fields.Name"] = "Name",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Fields.Name.Hint"] = "The name of the specification attribute group.",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Fields.Name.Required"] = "Please provide a name.",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Info"] = "Attribute group info",
                ["Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttributeGroup.Updated"] = "The attribute group has been updated successfully.",
                ["Admin.Catalog.Products.SpecificationAttributes.NameFormat"] = "{0} >> {1}",
                ["Admin.System.Warnings.PluginsOverrideSameService"] = "The \"{0}\" interface/class has been overridden in those assemblies: {1}. This situation may cause errors because there is only one of them will be used (Please contact the assembly(ies) developers to solve this problem.)",

                //<MFA #475>
                ["Admin.Configuration.Authentication"] = "Authentication",
                ["Admin.Configuration.Authentication.MultiFactorMethods"] = "Multi-factor authentication",
                ["Admin.Configuration.Authentication.MultiFactorMethods.BackToList"] = "back to multi-factor authentication method list",
                ["Admin.Configuration.Authentication.MultiFactorMethods.Configure"] = "Configure",
                ["Admin.Configuration.Authentication.MultiFactorMethods.Fields.DisplayOrder"] = "Display order",
                ["Admin.Configuration.Authentication.MultiFactorMethods.Fields.FriendlyName"] = "Friendly name",
                ["Admin.Configuration.Authentication.MultiFactorMethods.Fields.IsActive"] = "Is active",
                ["Admin.Configuration.Authentication.MultiFactorMethods.Fields.SystemName"] = "System name",

                ["Permission.Authentication.ManageMultifactorMethods"] = "Admin area. Manage Multi-factor Authentication Methods",

                ["MultiFactorAuthentication.Notification.SelectedMethodIsNotActive"] = "The multi-factor authentication provider specified in your account settings has been deactivated. Please contact your administrator.",

                ["PageTitle.MultiFactorAuthentication"] = "Multi-factor authentication",
                ["PageTitle.MultiFactorVerification"] = "Multi-factor verification",
                ["Account.MultiFactorAuthentication.Fields.IsEnabled"] = "Is enabled",
                ["Account.MultiFactorAuthentication.Settings"] = "Settings",
                ["Account.MultiFactorAuthentication.Providers"] = "Authentication providers",
                ["Account.MultiFactorAuthentication.Providers.NoActive"] = "No active providers",
                ["Account.MultiFactorAuthentication.Description"] = "<p>To activate multi-factor authentication for your account, you need: </p></br><ol><li>1. Activate the ’Is enabled’ setting.</li><li>2. Choose one of the multi-factor authentication providers.</li><li>3. Save.</li><li>4. Configure the selected multi-factor authentication provider by following the instructions on the individual settings page of the selected provider.</li></ol></br><p> WARNING. After saving the selected provider, be sure to configure it, otherwise you will be denied access the next time you try to enter your account.</p>",
                //</MFA #475>

                ["Admin.Configuration.Plugins.Description.DownloadMorePlugins"] = "You can download more nopCommerce plugins in our <a href=\"https://www.nopcommerce.com/marketplace?utm_source=admin-panel&utm_medium=menu&utm_campaign=marketplace&utm_content=all-plugins\" target=\"_blank\">marketplace</a>",
                ["Admin.Configuration.Payment.Methods.DownloadMorePlugins"] = "You can download more plugins in our <a href=\"https://www.nopcommerce.com/extensions?category=payment-modules&utm_source=admin-panel&utm_medium=menu&utm_campaign=marketplace&utm_content=payment-plugins\" target=\"_blank\">marketplace</a>",
                ["Admin.Configuration.Shipping.Providers.DownloadMorePlugins"] = "You can download more plugins in our <a href=\"https://www.nopcommerce.com/extensions?category=shipping-delivery&utm_source=admin-panel&utm_medium=menu&utm_campaign=marketplace&utm_content=shipping-plugins\" target=\"_blank\">marketplace</a>",
                ["Admin.Configuration.Tax.Providers.DownloadMorePlugins"] = "You can download more plugins in our <a href=\"https://www.nopcommerce.com/extensions?category=taxes&utm_source=admin-panel&utm_medium=menu&utm_campaign=marketplace&utm_content=tax-plugins\" target=\"_blank\">marketplace</a>",
                ["Admin.Configuration.Settings.GeneralCommon.DefaultStoreTheme.GetMore"] = "You can get more themes in our <a href=\"https://www.nopcommerce.com/themes?utm_source=admin-panel&utm_medium=menu&utm_campaign=marketplace&utm_content=general-common-theme\" target=\"_blank\">marketplace</a>",
                ["Admin.Configuration.Plugins.OfficialFeed.Instructions"] = "Here you can find third-party extensions and themes which are developed by our community and partners. They are also available in our <a href=\"https://www.nopcommerce.com/marketplace?utm_source=admin-panel&utm_medium=menu&utm_campaign=marketplace&utm_content=official-plugins\" target=\"_blank\">marketplace</a>",
                ["Admin.Catalog.Attributes.CheckoutAttributes.Values.AddNew"] = "Add a new checkout attribute value",

                ["Admin.Configuration.Settings.Catalog.OneReviewPerProductFromCustomer"] = "One review per product from customer",
                ["Admin.Configuration.Settings.Catalog.OneReviewPerProductFromCustomer.Hint"] = "Check to restrict customer to add just 1 review per product.",
                ["Reviews.AlreadyAddedProductReviews"] = "Product review is already added for this product",
                ["Admin.Configuration.Plugins.ChangesApplyAfterReboot"] = "Changes will be applied after restart application",
                ["Admin.Configuration.Plugins.Fields.IsEnabled"] = "Enabled",
                ["Admin.Customers.ActivityLog.Fields.IpAddress.Hint"] = "A customer IP address.",
                ["Plugins.Widgets.GoogleAnalytics.UseJsToSendEcommerceInfo"] = "Use JS to send eCommerce info",
                ["Plugins.Widgets.GoogleAnalytics.UseJsToSendEcommerceInfo.Hint"] = "Check to use JS code to send eCommerce info from the order completed page. But in case of redirection payment methods some customers may skip it. Otherwise, eCommerce information will be sent using HTTP request. Information is sent each time an order is paid but UTM is not supported in this mode.",
                ["Plugins.Widgets.GoogleAnalytics.IncludeCustomerId"] = "Include customer ID",
                ["Plugins.Widgets.GoogleAnalytics.IncludeCustomerId.Hint"] = "Check to include customer identifier to script.",
                ["Admin.Configuration.Plugins.DiscardChanges"] = "Discard changes",
                ["Admin.Configuration.Plugins.DiscardChanges.Progress"] = "Discarding changes on plugins...",
                ["Admin.Configuration.Plugins.ApplyChanges"] = "Restart application to apply changes",
                ["Admin.Configuration.Plugins.ApplyChanges.Progress"] = "Applying changes on plugins...",
                ["Products.EstimateShipping.NoSelectedShippingOption"] = "Please select the address you want to ship to",
                ["Admin.Configuration.Settings.CustomerUser.ForceMultifactorAuthentication"] = "Force multi-factor authentication",
                ["Admin.Configuration.Settings.CustomerUser.ForceMultifactorAuthentication.Hint"] = "Force activation of multi-factor authentication for all users (at least one MFA provider must be active).",
                ["Account.MultiFactorAuthentication.Warning.ForceActivation"] = "Enforce multi-factor authentication for all users is enabled.",
                ["Admin.Configuration.Settings.CustomerUser.ForceMultifactorAuthentication.Warning"] = "There are currently no active authentication providers. To use this setting, you must activate one of the multi-factor authentication providers.",

                //#1730
                ["Admin.Configuration.AppSettings.Installation.InstallRegionalResources"] = "Install regional resources",
                ["Admin.Configuration.AppSettings.Installation.InstallRegionalResources.Hint"] = "Enable this setting to download and setup the regional language pack during installation.",

                //#5213
                ["Admin.System.Log.List.PremiumSupport"] = "Have questions or need help? Get dedicated support from the nopCommerce team with a guaranteed response within 24 hours. Please find more about our premium support services <a href=\"https://www.nopcommerce.com/nopcommerce-premium-support-services?utm_source=admin-panel&utm_medium=menu&utm_campaign=premium_support&utm_content=log-list\" target=\"_blank\">here</a>.",
                ["Admin.System.Log.PremiumSupport"] = "Have questions or need help? Get dedicated support from the nopCommerce team with a guaranteed response within 24 hours. Please find more about our premium support services <a href=\"https://www.nopcommerce.com/nopcommerce-premium-support-services?utm_source=admin-panel&utm_medium=menu&utm_campaign=premium_support&utm_content=log-details\" target=\"_blank\">here</a>.",

                //configuration steps tour
                ["Admin.ConfigurationSteps"] = "Start accepting orders",
                ["Admin.ConfigurationSteps.Welcome.Title"] = "Welcome to your store!",
                ["Admin.ConfigurationSteps.Welcome.Text"] = "Can’t wait to start accepting orders? Let us show you how to set up your store fast and easy. The steps below describe the most important settings for the online shop. With our tips on each page you will see how clear this process is. You will be ready to start selling immediately after you go through these steps. So good luck!",
                ["Admin.ConfigurationSteps.PersonalizeStore.Title"] = "Personalize your store",
                ["Admin.ConfigurationSteps.PersonalizeStore.Description"] = "Choose a beautiful theme for your store and add your logo",
                ["Admin.ConfigurationSteps.AddStoreInfo.Title"] = "Add your store info",
                ["Admin.ConfigurationSteps.AddStoreInfo.Description"] = "Enter your store details and protect your customers using SSL",
                ["Admin.ConfigurationSteps.SetUpShipping.Title"] = "Set up shipping",
                ["Admin.ConfigurationSteps.SetUpShipping.Description"] = "Set up shipping methods to deliver orders to customers",
                ["Admin.ConfigurationSteps.SetUpPayments.Title"] = "Set up payments",
                ["Admin.ConfigurationSteps.SetUpPayments.Description"] = "Choose how your customers will pay for their orders",
                ["Admin.ConfigurationSteps.SetUpTaxes.Title"] = "Set up taxes",
                ["Admin.ConfigurationSteps.SetUpTaxes.Description"] = "Configure rates manually or choose a tax service to automate all tax things",
                ["Admin.ConfigurationSteps.CreateProducts.Title"] = "Create products",
                ["Admin.ConfigurationSteps.CreateProducts.Description"] = "Build a catalog with attractive product descriptions and pictures",
                ["Admin.ConfigurationSteps.CreateEmailAccounts.Title"] = "Set up email accounts",
                ["Admin.ConfigurationSteps.CreateEmailAccounts.Description"] = "It allows you to send notifications to your customers",
                ["Admin.ConfigurationSteps.EditServicesInfo.Title"] = "Edit services info",
                ["Admin.ConfigurationSteps.EditServicesInfo.Description"] = "Add info pages describing shipping, return policy and more",
                ["Admin.ConfigurationSteps.PoweredBy.Title"] = "“Powered by” link",
                ["Admin.ConfigurationSteps.PoweredBy.Description"] = "Remove the “Powered by nopCommerce” link from the footer",
                ["Admin.ConfigurationSteps.Back"] = "Back",
                ["Admin.ConfigurationSteps.NextStep"] = "Next",
                ["Admin.ConfigurationSteps.NextPage"] = "Next page",
                ["Admin.ConfigurationSteps.Done"] = "Done",
                ["Admin.ConfigurationSteps.PersonalizeStore.Intro.Title"] = "Configuration tour",
                ["Admin.ConfigurationSteps.PersonalizeStore.Intro.Text"] = "Let us help you to configure your store! We will share a few tips, describing the most important fields for the initial configuration.",
                ["Admin.ConfigurationSteps.PersonalizeStore.BasicAdvanced.Title"] = "“Basic/Advanced” modes",
                ["Admin.ConfigurationSteps.PersonalizeStore.BasicAdvanced.Text"] = "This two-position <b>Basic/Advanced</b> switch allows you to switch between the page display modes. For convenience of use, the most frequent settings are shown in the Basic mode. If you cannot find a required setting on a page, switch to the Advanced mode to see all the available settings.",
                ["Admin.ConfigurationSteps.PersonalizeStore.Theme.Title"] = "Choose a theme",
                ["Admin.ConfigurationSteps.PersonalizeStore.Theme.Text"] = "On this page, you can set up your store theme. After you choose a theme on our <a href=\"https://www.nopcommerce.com/marketplace?utm_source=admin-panel&utm_medium=menu&utm_campaign=marketplace&utm_content=all-plugins\" target=\"_blank\">marketplace</a>, upload it on your site following <a href=\"https://docs.nopcommerce.com/getting-started/design-your-store/choose-and-install-a-theme.html?utm_source=admin-panel&utm_medium=tour&utm_campaign=documentation&utm_content=tooltip\" target=\"_blank\">these instructions</a>. Then refresh this page, and you will see all the available themes. Choose one and click the <b>Save</b> button in the top right.",
                ["Admin.ConfigurationSteps.PersonalizeStore.Logo.Title"] = "Upload your logo",
                ["Admin.ConfigurationSteps.PersonalizeStore.Logo.Text"] = "In this field, click the <b>Upload a file</b> button, then choose your logo file.",
                ["Admin.ConfigurationSteps.EmailAccount.EmailAddress.Title"] = "Email address",
                ["Admin.ConfigurationSteps.EmailAccount.EmailAddress.Text"] = "Enter the “from” email address for all outgoing emails of your store. Example: sales@yourstore.com.",
                ["Admin.ConfigurationSteps.EmailAccount.DisplayName.Title"] = "Email display name",
                ["Admin.ConfigurationSteps.EmailAccount.DisplayName.Text"] = "Enter the displayed name for outgoing emails of your store. For example, “Your store sales department”.",
                ["Admin.ConfigurationSteps.EmailAccount.Host.Title"] = "Host",
                ["Admin.ConfigurationSteps.EmailAccount.Host.Text"] = "This is the host name or IP address of your mail server. You can normally find this out from your ISP or web host.",
                ["Admin.ConfigurationSteps.EmailAccount.Port.Title"] = "Port",
                ["Admin.ConfigurationSteps.EmailAccount.Port.Text"] = "Enter the SMTP port of your email server. This is usually port 25.",
                ["Admin.ConfigurationSteps.EmailAccount.Username.Title"] = "Username",
                ["Admin.ConfigurationSteps.EmailAccount.Username.Text"] = "Enter the user name which is used to authenticate to your email server.",
                ["Admin.ConfigurationSteps.EmailAccount.Password.Title"] = "Password",
                ["Admin.ConfigurationSteps.EmailAccount.Password.Text"] = "This is the password you use to authenticate to your mail server.",
                ["Admin.ConfigurationSteps.EmailAccount.UseSsl.Title"] = "Use SSL",
                ["Admin.ConfigurationSteps.EmailAccount.UseSsl.Text"] = "Check to use Secure Sockets Layer (SSL) to encrypt the SMTP connection.",
                ["Admin.ConfigurationSteps.EmailAccount.DefaultCredentials.Title"] = "Use default credentials",
                ["Admin.ConfigurationSteps.EmailAccount.DefaultCredentials.Text"] = "Check to use default credentials for the connection.",
                ["Admin.ConfigurationSteps.EmailAccount.TestEmail.Title"] = "Send test email",
                ["Admin.ConfigurationSteps.EmailAccount.TestEmail.Text"] = "Enter your email address and send a test email to make sure you set the email account right.",
                ["Admin.ConfigurationSteps.EmailAccountList.EmailAccounts1.Title"] = "Email accounts",
                ["Admin.ConfigurationSteps.EmailAccountList.EmailAccounts1.Text"] = "You can see all the existing email accounts on this page. Only one email account is created automatically during the installation process. You can also create a general contact email, a sales representative email, a customer support email, and more to contact your customers.",
                ["Admin.ConfigurationSteps.EmailAccountList.EmailAccounts2.Title"] = "Email accounts",
                ["Admin.ConfigurationSteps.EmailAccountList.EmailAccounts2.Text"] = "Then, these email accounts will be used to send order notifications, registration emails, and newsletters to your customers. But you may as well use only one email account for all these purposes.",
                ["Admin.ConfigurationSteps.EmailAccountList.DefaultEmailAccount.Title"] = "Default email account",
                ["Admin.ConfigurationSteps.EmailAccountList.DefaultEmailAccount.Text"] = "Don’t forget to mark one of the existing email accounts as the default one.",
                ["Admin.ConfigurationSteps.EmailAccountList.Edit.Title"] = "Edit an email account",
                ["Admin.ConfigurationSteps.EmailAccountList.Edit.Text"] = "To edit an email account click the <b>Edit</b> button.",
                ["Admin.ConfigurationSteps.PaymentMethods.PaymentMethods.Title"] = "Payment methods",
                ["Admin.ConfigurationSteps.PaymentMethods.PaymentMethods.Text"] = "You can see all the payment methods (plugins) allowed to use in your store on this page. However, you can always find much more in our marketplace.",
                ["Admin.ConfigurationSteps.PaymentMethods.CheckMoney.Title"] = "Check/money order",
                ["Admin.ConfigurationSteps.PaymentMethods.CheckMoney.Text"] = "Check/money orders are often used by government agencies or large businesses. Rather than paying directly through your site, shoppers will request that you send them a Purchase order (PO), and they will send the payment back. Most of the order processing is handled outside of the software. This method is already enabled.",
                ["Admin.ConfigurationSteps.PaymentMethods.Manual.Title"] = "Credit card (manual)",
                ["Admin.ConfigurationSteps.PaymentMethods.Manual.Text"] = "This is a special payment plugin that allows all orders to be successfully entered on the website, but it does NOT really charge a customer or make any calls to any live payment gateway. This payment method is recommended if you want to perform one of the following: <ul><li>Process all orders offline</li><li>Process them manually via another back-office system</li><li>Test the site end-to-end before going live</li></ul>",
                ["Admin.ConfigurationSteps.PaymentMethods.PayPal.Title"] = "PayPal Smart Payment Buttons",
                ["Admin.ConfigurationSteps.PaymentMethods.PayPal.Text"] = "If you want to process payments online, we’d recommend you to set up the PayPal Smart Payment Buttons payment method. PayPal Checkout with Smart Payment Buttons gives your buyers a simplified and secure checkout experience. Read more about how to set this plugin <a href=\"https://docs.nopcommerce.com/getting-started/configure-payments/payment-methods/paypal-smart-payment-buttons.html?utm_source=admin-panel&utm_medium=tour&utm_campaign=documentation&utm_content=tooltip\" target=\"_blank\">here</a>.",
                ["Admin.ConfigurationSteps.PaymentMethods.Configure.Title"] = "Configure a payment method",
                ["Admin.ConfigurationSteps.PaymentMethods.Configure.Text"] = "You can configure each payment method by clicking the appropriate <b>Configure</b> button.",
                ["Admin.ConfigurationSteps.Product.SettingsButton.Title"] = "“Settings” button",
                ["Admin.ConfigurationSteps.Product.SettingsButton.Text"] = "This “Settings” button allows you to set up the basic mode to choose which fields you want to be shown exactly on the product edit page.",
                ["Admin.ConfigurationSteps.Product.Details.Title"] = "Product details",
                ["Admin.ConfigurationSteps.Product.Details.Text"] = "Enter the relevant product details in these fields. The screenshot below shows how they will be displayed on the product page with the default nopCommerce theme: <div><img src=\"../../js/admintour/images/product-page.jpg\"/></div>",
                ["Admin.ConfigurationSteps.Product.Price.Title"] = "Product price",
                ["Admin.ConfigurationSteps.Product.Price.Text"] = "Enter the product price in a predefined currency here. Read more on how to manage currencies <a href=\"https://docs.nopcommerce.com/getting-started/configure-payments/advanced-configuration/currencies.html?utm_source=admin-panel&utm_medium=tour&utm_campaign=documentation&utm_content=tooltip\" target=\"_blank\">here</a>.",
                ["Admin.ConfigurationSteps.Product.Tax.Title"] = "Product tax category",
                ["Admin.ConfigurationSteps.Product.Tax.Text"] = "Select the product tax category or tick the <b>Tax exempt</b> if needed.",
                ["Admin.ConfigurationSteps.Product.Shipping.Title"] = "Product shipping info",
                ["Admin.ConfigurationSteps.Product.Shipping.Text"] = "Define product-specific shipping details in this panel.",
                ["Admin.ConfigurationSteps.Product.Inventory.Title"] = "Product inventory",
                ["Admin.ConfigurationSteps.Product.Inventory.Text"] = "Enter the product inventory info here. <br> <ul><li>The <b>Don’t track inventory</b> option allows you to opt for no tracking</li><li>The <b>Track inventory</b> option is for those who don’t have product variants and need to know just how many items are left</li><li>The <b>Track inventory by product attributes</b> option is best for you if you have different product attributes combinations and need to track their stock quantities</li></ul>",
                ["Admin.ConfigurationSteps.Product.Pictures.Title"] = "Product pictures",
                ["Admin.ConfigurationSteps.Product.Pictures.Text"] = "You can add pictures to your product after you save it for the first time. Click the <b>Save</b> button in the top right and then proceed to the pictures panel.",
                ["Admin.ConfigurationSteps.ConfigureManual.Switch.Title"] = "“Fixed rate/By weight” switch",
                ["Admin.ConfigurationSteps.ConfigureManual.Switch.Text"] = "The “Fixed rate/By weight” switch allows you to choose the type of shipping rates you’d like to use in your store.",
                ["Admin.ConfigurationSteps.ConfigureManual.FixedRate.Title"] = "“Fixed rate” option",
                ["Admin.ConfigurationSteps.ConfigureManual.FixedRate.Text"] = "The fixed shipping rate option allows you to set shipping cost depending on the shipping method.",
                ["Admin.ConfigurationSteps.ConfigureManual.ByWeight.Title"] = "“By weight” option",
                ["Admin.ConfigurationSteps.ConfigureManual.ByWeight.Text"] = "The shipping by weight and by total options allow setting different shipping fees based on shipment weight and total.",
                ["Admin.ConfigurationSteps.ConfigureManual.Methods.Title"] = "Shipping methods",
                ["Admin.ConfigurationSteps.ConfigureManual.Methods.Text"] = "This table contains shipping methods used by offline shipping providers. A few shipping methods are created automatically during the installation process.",
                ["Admin.ConfigurationSteps.ConfigureManual.Edit.Title"] = "Edit rate",
                ["Admin.ConfigurationSteps.ConfigureManual.Edit.Text"] = "Click the <b>Edit</b> button to edit a rate for a specific shipping method.",
                ["Admin.ConfigurationSteps.ConfigureManual.Manage.Title"] = "Manage shipping methods",
                ["Admin.ConfigurationSteps.ConfigureManual.Manage.Text"] = "Using this button, you can add new shipping methods or delete the existing ones.",
                ["Admin.ConfigurationSteps.ShippingProviders.Providers.Title"] = "Shipping providers",
                ["Admin.ConfigurationSteps.ShippingProviders.Providers.Text"] = "You can see all the shipping providers (plugins) allowed to use in your store on this page. However, you can always find much more in our <a href=\"https://www.nopcommerce.com/extensions?category=shipping-delivery&utm_source=admin-panel&utm_medium=tour&utm_campaign=marketplace&utm_content=tooltip\" target=\"_blank\">marketplace</a>.",
                ["Admin.ConfigurationSteps.ShippingProviders.Manual.Title"] = "Manual shipping provider",
                ["Admin.ConfigurationSteps.ShippingProviders.Manual.Text"] = "The only active shipping plugin by default is <b>Manual</b>. This provider allows you to configure shipping methods and rates manually.",
                ["Admin.ConfigurationSteps.ShippingProviders.ShipStation.Title"] = "ShipStation",
                ["Admin.ConfigurationSteps.ShippingProviders.ShipStation.Text"] = "If you want to provide more accurate shipping rates, we recommend using shipping services such as ShipStation. Read how to configure it in <a href=\"https://docs.nopcommerce.com/getting-started/configure-shipping/shipping-providers/shipstation.html?utm_source=admin-panel&utm_medium=tour&utm_campaign=documentation&utm_content=tooltip\" target=\"_blank\">this article</a>.",
                ["Admin.ConfigurationSteps.ShippingProviders.Configure.Title"] = "Configure Manual",
                ["Admin.ConfigurationSteps.ShippingProviders.Configure.Text"] = "Now we’ll configure the Manual shipping provider. Click this button to proceed to the plugin configuration page.",
                ["Admin.ConfigurationSteps.Store.Name.Title"] = "Your store name",
                ["Admin.ConfigurationSteps.Store.Name.Text"] = "Enter your store name in this field. It will be displayed, for instance, in the newsletter and notification emails sent to your customers.",
                ["Admin.ConfigurationSteps.Store.Url.Title"] = "Your store URL",
                ["Admin.ConfigurationSteps.Store.Url.Text"] = "Enter your store URL in this field. For example, it could be http://www.yourstore.com/ or https://www.yourstore.com/mystore/ if you installed your store in a subdirectory.",
                ["Admin.ConfigurationSteps.Store.Ssl.Title"] = "Enable SSL",
                ["Admin.ConfigurationSteps.Store.Ssl.Text"] = "If you already have an SSL certificate installed on the server, enable SSL to protect your customers’ data. <b>Do not enable it if you don’t have an SSL certificate installed yet!</b> SSL Certificates provide customer trust and improve site rankings. Note that some online payment methods require an SSL certificate installed for correct working. Read how to install and configure SSL certification <a href=\"https://docs.nopcommerce.com/getting-started/advanced-configuration/how-to-install-and-configure-ssl-certification.html?utm_source=admin-panel&utm_medium=tour&utm_campaign=documentation&utm_content=tooltip\" target=\"_blank\">here</a>.",
                ["Admin.ConfigurationSteps.TaxManual.Switch.Title"] = "“Fixed rate/By country” switch",
                ["Admin.ConfigurationSteps.TaxManual.Switch.Text"] = "The “Fixed rate/By country” switch allows you to choose the type of tax rates you’d like to use in your store.",
                ["Admin.ConfigurationSteps.TaxManual.Fixed.Title"] = "“Fixed rate” option",
                ["Admin.ConfigurationSteps.TaxManual.Fixed.Text"] = "The “Fixed tax rate” option allows you to set tax rates depending on the tax category.",
                ["Admin.ConfigurationSteps.TaxManual.ByCountry.Title"] = "“By country” option",
                ["Admin.ConfigurationSteps.TaxManual.ByCountry.Text"] = "The tax rates “By country/state/zip” option allows setting different tax rates based on a country, state, or zip.",
                ["Admin.ConfigurationSteps.TaxManual.Categories.Title"] = "Tax categories",
                ["Admin.ConfigurationSteps.TaxManual.Categories.Text"] = "This table contains tax categories used by offline tax providers. A few tax categories are created automatically during the installation process.",
                ["Admin.ConfigurationSteps.TaxManual.Edit.Title"] = "Edit tax rate",
                ["Admin.ConfigurationSteps.TaxManual.Edit.Text"] = "Click the <b>Edit</b> button to edit a tax rate for the specific tax category.",
                ["Admin.ConfigurationSteps.TaxProviders.TaxProviders.Title"] = "Tax providers",
                ["Admin.ConfigurationSteps.TaxProviders.TaxProviders.Text"] = "You can see all the tax providers (plugins) allowed to use in your store on this page. However, you can always find much more in our <a href=\"https://www.nopcommerce.com/extensions?category=taxes&utm_source=admin-panel&utm_medium=tour&utm_campaign=marketplace&utm_content=tooltip\" target=\"_blank\">marketplace</a>.",
                ["Admin.ConfigurationSteps.TaxProviders.Avalara.Title"] = "Avalara tax provider",
                ["Admin.ConfigurationSteps.TaxProviders.Avalara.Text"] = "You can automate the tax compliance in your store. Set up the Avalara tax provider, and you won’t need to worry about taxes anymore. Avalara is an automated tax compliance software. Read how to configure it in <a href=\"https://docs.nopcommerce.com/getting-started/configure-taxes/tax-providers/avalara.html?utm_source=admin-panel&utm_medium=tour&utm_campaign=documentation&utm_content=tooltip\" target=\"_blank\">this article</a>.",
                ["Admin.ConfigurationSteps.TaxProviders.Manual.Title"] = "Manual tax provider",
                ["Admin.ConfigurationSteps.TaxProviders.Manual.Text"] = "Manual tax provider allows you to set up fixed tax rates depending on the country/state/zip.",
                ["Admin.ConfigurationSteps.TaxProviders.PrimaryProvider.Title"] = "Mark as a primary provider",
                ["Admin.ConfigurationSteps.TaxProviders.PrimaryProvider.Text"] = "You can mark the desired tax provider as a primary one using the <b>Mark as primary provider</b> button.",
                ["Admin.ConfigurationSteps.TaxProviders.Configure.Title"] = "Configure Manual",
                ["Admin.ConfigurationSteps.TaxProviders.Configure.Text"] = "Now we’ll configure the Manual tax provider. Click the <b>Edit</b> button to proceed to the plugin configuration page.",
                ["Admin.ConfigurationSteps.Topic.TitleContent.Title"] = "Title and content",
                ["Admin.ConfigurationSteps.Topic.TitleContent.Text"] = "Enter a topic (page) title and its content in this field. This is what customers will see in the public store.",
                ["Admin.ConfigurationSteps.Topic.Preview.Title"] = "Preview the page",
                ["Admin.ConfigurationSteps.Topic.Preview.Text"] = "To find out how your customers will see the page, click the <b>Preview</b> button.",
                ["Admin.ConfigurationSteps.TopicList.Topics1.Title"] = "Topics (pages)",
                ["Admin.ConfigurationSteps.TopicList.Topics1.Text"] = "Topics (pages) are free-form content blocks that can be displayed on your site, either embedded within other pages or on their own pages. They are often used for FAQ pages, policy pages, special instructions, and more.",
                ["Admin.ConfigurationSteps.TopicList.Topics2.Title"] = "Topics (pages)",
                ["Admin.ConfigurationSteps.TopicList.Topics2.Text"] = "In this table, you can see a list of the topics created by default.",
                ["Admin.ConfigurationSteps.TopicList.Shipping.Title"] = "Shipping info",
                ["Admin.ConfigurationSteps.TopicList.Shipping.Text"] = "For example, this is a shipping info topic. It contains shipping information that customers can access by clicking the appropriate link in your store.",
                ["Admin.ConfigurationSteps.TopicList.Location.Title"] = "Page link location",
                ["Admin.ConfigurationSteps.TopicList.Location.Text"] = "As you can see, this topic is included in the first column of the footer.",
                ["Admin.ConfigurationSteps.TopicList.Edit.Title"] = "Edit the page",
                ["Admin.ConfigurationSteps.TopicList.Edit.Text"] = "To edit this page, click the <b>Edit</b> button. You can also create a new topic by clicking the <b>Add new</b> button at the top of the page.",
                ["Admin.ConfigurationSteps.ShippingProviders.Activate.Text"] = "To activate a shipping provider click the <b>Edit</b> button, then tick the <b>Is active</b> checkbox and save the changes.",
                ["Admin.ConfigurationSteps.ShippingProviders.Activate.Title"] = "Activate a provider",
                ["Admin.ConfigurationSteps.PaymentMethods.Activate.Text"] = "To activate a payment method click the <b>Edit</b> button, then tick the <b>Is active</b> checkbox and save the changes.",
                ["Admin.ConfigurationSteps.PaymentMethods.Activate.Title"] = "Activate a payment method",
                ["Admin.Configuration.AppSettings.Description"] = "Configuration in ASP.NET Core is performed using a configuration provider from the external appsettings.json configuration file. These settings are used when the application is launched, so after editing them, the application will be restarted. You can find a detailed description of all configuration parameters in <a href=\"https://docs.nopcommerce.com/developer/tutorials/description-of-settings-from-appsettings-json-file-and-NopConfig-class.html\" target=\"_blank\">our documentation.</a>",
            }).Wait();

            // rename locales
            var localesToRename = new[]
            {
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Added", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Added" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.AddNew", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.AddNew" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.BackToList", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.BackToList" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Deleted", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Deleted" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.EditAttributeDetails", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.EditAttributeDetails" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Fields.DisplayOrder", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Fields.DisplayOrder" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Fields.DisplayOrder.Hint", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Fields.DisplayOrder.Hint" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Fields.Name", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Fields.Name" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Fields.Name.Hint", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Fields.Name.Hint" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Fields.Name.Required", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Fields.Name.Required" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Info", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Info" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.AddNew", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.AddNew" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.EditOptionDetails", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.EditOptionDetails" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.Fields.ColorSquaresRgb", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.Fields.ColorSquaresRgb" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.Fields.ColorSquaresRgb.Hint", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.Fields.ColorSquaresRgb.Hint" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.Fields.DisplayOrder", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.Fields.DisplayOrder" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.Fields.DisplayOrder.Hint", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.Fields.DisplayOrder.Hint" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.Fields.EnableColorSquaresRgb", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.Fields.EnableColorSquaresRgb" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.Fields.EnableColorSquaresRgb.Hint", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.Fields.EnableColorSquaresRgb.Hint" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.Fields.Name", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.Fields.Name" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.Fields.Name.Hint", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.Fields.Name.Hint" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.Fields.Name.Required", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.Fields.Name.Required" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.Fields.NumberOfAssociatedProducts", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.Fields.NumberOfAssociatedProducts" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Options.SaveBeforeEdit", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Options.SaveBeforeEdit" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.Updated", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.Updated" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.UsedByProducts", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.UsedByProducts" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.UsedByProducts.Product", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.UsedByProducts.Product" },
                new { Name = "Admin.Catalog.Attributes.SpecificationAttributes.UsedByProducts.Published", NewName = "Admin.Catalog.Attributes.SpecificationAttributes.SpecificationAttribute.UsedByProducts.Published" },
                //<MFA #475>
                new { Name = "Admin.Configuration.ExternalAuthenticationMethods.Fields.DisplayOrder", NewName = "Admin.Configuration.Authentication.ExternalMethods.Fields.DisplayOrder"},
                new { Name = "Admin.Configuration.ExternalAuthenticationMethods.Fields.FriendlyName", NewName = "Admin.Configuration.Authentication.ExternalMethods.Fields.FriendlyName"},
                new { Name = "Admin.Configuration.ExternalAuthenticationMethods.Fields.IsActive", NewName = "Admin.Configuration.Authentication.ExternalMethods.Fields.IsActive"},
                new { Name = "Admin.Configuration.ExternalAuthenticationMethods.Fields.SystemName", NewName = "Admin.Configuration.Authentication.ExternalMethods.Fields.SystemName"},
                new { Name = "Admin.Configuration.ExternalAuthenticationMethods.BackToList", NewName = "Admin.Configuration.Authentication.ExternalMethods.BackToList"},
                new { Name = "Admin.Configuration.ExternalAuthenticationMethods.Configure", NewName = "Admin.Configuration.Authentication.ExternalMethods.Configure"},
                new { Name = "Admin.Configuration.ExternalAuthenticationMethods", NewName = "Admin.Configuration.Authentication.ExternalMethods"},
                new { Name = "Permission.ManageExternalAuthenticationMethods", NewName = "Permission.Authentication.ManageExternalMethods"},
                //</MFA #475>
            };

            var languageService = EngineContext.Current.Resolve<ILanguageService>();
            var languages = languageService.GetAllLanguagesAsync(true).Result;
            foreach (var lang in languages)
            {
                foreach (var locale in localesToRename)
                {
                    var lsr = localizationService.GetLocaleStringResourceByNameAsync(locale.Name, lang.Id, false).Result;
                    if (lsr != null)
                    {
                        lsr.ResourceName = locale.NewName;
                        localizationService.UpdateLocaleStringResourceAsync(lsr).Wait();
                    }
                }
            }
        }

        /// <summary>Collects the DOWN migration expressions</summary>
        public override void Down()
        {
            //add the downgrade logic if necessary 
        }
    }
}
