name: mydotnet project  # ✅ Workflow name shown in GitHub Actions tab

on:
  push:
    branches:
      - develop  # ✅ Trigger workflow only when code is pushed to 'develop' branch

jobs:
  dotnet_publish:  # ✅ Job name
    runs-on: self-hosted  # ✅ Use your own runner instead of GitHub-hosted

    steps:
      - name: Checkout code  # ✅ Step 1: Clone your repo into the runner
        uses: actions/checkout@v4

      - name: Setup .NET  # ✅ Step 2: Install specific .NET SDK version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.111'  # ✅ Make sure this version matches your project SDK

      - name: Publish .NET Project  # ✅ Step 3: Build and publish the project
        run: dotnet publish -c Release src/Presentation/Nop.Web/Nop.Web.csproj -o ./publish
        # ✅ '-c Release' = build in Release mode
        # ✅ '-o ./publish' = output compiled files to the 'publish' folder
