using FluentMigrator;
using Nop.Core.Domain.Messages;
using Nop.Data;
using Nop.Data.Migrations;
using Nop.Web.Framework.Extensions;

namespace Nop.Web.Framework.Migrations.UpgradeTo500;

[NopUpdateMigration("2026-04-14 00:00:00", "5.00", UpdateMigrationType.Localization)]
public class LocalizationMigration : MigrationBase
{
    /// <summary>Collect the UP migration expressions</summary>
    public override void Up()
    {
        if (!DataSettingsManager.IsDatabaseInstalled())
            return;

        #region Delete locales

        this.DeleteLocaleResources(new List<string>
        {
            //#7340
            "ActivityLog.AddNewNews",
            "ActivityLog.DeleteNews",
            "ActivityLog.DeleteNewsComment",
            "ActivityLog.EditNews",
            "ActivityLog.EditNewsComment",
            "ActivityLog.PublicStore.AddNewsComment",
            "Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnNewsCommentPage",
            "Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnNewsCommentPage.Hint",
            "Admin.Configuration.Settings.GeneralCommon.SitemapIncludeNews",
            "Admin.Configuration.Settings.GeneralCommon.SitemapIncludeNews.Hint",
            "Admin.Configuration.Settings.News",
            "Admin.Configuration.Settings.News.AllowNotRegisteredUsersToLeaveComments",
            "Admin.Configuration.Settings.News.AllowNotRegisteredUsersToLeaveComments.Hint",
            "Admin.Configuration.Settings.News.BlockTitle.Common",
            "Admin.Configuration.Settings.News.BlockTitle.NewsComments",
            "Admin.Configuration.Settings.News.Enabled",
            "Admin.Configuration.Settings.News.Enabled.Hint",
            "Admin.Configuration.Settings.News.MainPageNewsCount",
            "Admin.Configuration.Settings.News.MainPageNewsCount.Hint",
            "Admin.Configuration.Settings.News.NewsArchivePageSize",
            "Admin.Configuration.Settings.News.NewsArchivePageSize.Hint",
            "Admin.Configuration.Settings.News.NewsCommentsMustBeApproved",
            "Admin.Configuration.Settings.News.NewsCommentsMustBeApproved.Hint",
            "Admin.Configuration.Settings.News.NotifyAboutNewNewsComments",
            "Admin.Configuration.Settings.News.NotifyAboutNewNewsComments.Hint",
            "Admin.Configuration.Settings.News.ShowHeaderRSSUrl",
            "Admin.Configuration.Settings.News.ShowHeaderRSSUrl.Hint",
            "Admin.Configuration.Settings.News.ShowNewsCommentsPerStore",
            "Admin.Configuration.Settings.News.ShowNewsCommentsPerStore.Hint",
            "Admin.Configuration.Settings.News.ShowNewsOnMainPage",
            "Admin.Configuration.Settings.News.ShowNewsOnMainPage.Hint",
            "Admin.ContentManagement.News",
            "Admin.ContentManagement.News.Comments",
            "Admin.ContentManagement.News.Comments.ApproveSelected",
            "Admin.ContentManagement.News.Comments.DeleteSelected",
            "Admin.ContentManagement.News.Comments.DisapproveSelected",
            "Admin.ContentManagement.News.Comments.Fields.CommentText",
            "Admin.ContentManagement.News.Comments.Fields.CommentTitle",
            "Admin.ContentManagement.News.Comments.Fields.CreatedOn",
            "Admin.ContentManagement.News.Comments.Fields.Customer",
            "Admin.ContentManagement.News.Comments.Fields.IsApproved",
            "Admin.ContentManagement.News.Comments.Fields.NewsItem",
            "Admin.ContentManagement.News.Comments.Fields.StoreName",
            "Admin.ContentManagement.News.Comments.List.CreatedOnFrom",
            "Admin.ContentManagement.News.Comments.List.CreatedOnFrom.Hint",
            "Admin.ContentManagement.News.Comments.List.CreatedOnTo",
            "Admin.ContentManagement.News.Comments.List.CreatedOnTo.Hint",
            "Admin.ContentManagement.News.Comments.List.SearchApproved",
            "Admin.ContentManagement.News.Comments.List.SearchApproved.All",
            "Admin.ContentManagement.News.Comments.List.SearchApproved.ApprovedOnly",
            "Admin.ContentManagement.News.Comments.List.SearchApproved.DisapprovedOnly",
            "Admin.ContentManagement.News.Comments.List.SearchApproved.Hint",
            "Admin.ContentManagement.News.Comments.List.SearchText",
            "Admin.ContentManagement.News.Comments.List.SearchText.Hint",
            "Admin.ContentManagement.News.NewsItems",
            "Admin.ContentManagement.News.NewsItems.Added",
            "Admin.ContentManagement.News.NewsItems.AddNew",
            "Admin.ContentManagement.News.NewsItems.BackToList",
            "Admin.ContentManagement.News.NewsItems.Deleted",
            "Admin.ContentManagement.News.NewsItems.EditNewsItemDetails",
            "Admin.ContentManagement.News.NewsItems.Fields.AllowComments",
            "Admin.ContentManagement.News.NewsItems.Fields.AllowComments.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Comments",
            "Admin.ContentManagement.News.NewsItems.Fields.CreatedOn",
            "Admin.ContentManagement.News.NewsItems.Fields.EndDate",
            "Admin.ContentManagement.News.NewsItems.Fields.EndDate.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Full",
            "Admin.ContentManagement.News.NewsItems.Fields.Full.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Full.Required",
            "Admin.ContentManagement.News.NewsItems.Fields.Language",
            "Admin.ContentManagement.News.NewsItems.Fields.Language.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.LimitedToStores",
            "Admin.ContentManagement.News.NewsItems.Fields.LimitedToStores.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaDescription",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaDescription.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaKeywords",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaKeywords.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaTitle",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaTitle.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Published",
            "Admin.ContentManagement.News.NewsItems.Fields.Published.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.SeName",
            "Admin.ContentManagement.News.NewsItems.Fields.SeName.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Short",
            "Admin.ContentManagement.News.NewsItems.Fields.Short.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Short.Required",
            "Admin.ContentManagement.News.NewsItems.Fields.StartDate",
            "Admin.ContentManagement.News.NewsItems.Fields.StartDate.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Title",
            "Admin.ContentManagement.News.NewsItems.Fields.Title.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Title.Required",
            "Admin.ContentManagement.News.NewsItems.Info",
            "Admin.ContentManagement.News.NewsItems.List.SearchStore",
            "Admin.ContentManagement.News.NewsItems.List.SearchStore.Hint",
            "Admin.ContentManagement.News.NewsItems.List.SearchTitle",
            "Admin.ContentManagement.News.NewsItems.List.SearchTitle.Hint",
            "Admin.ContentManagement.News.NewsItems.Updated",
            "Admin.Documentation.Reference.News",
            "News",
            "News.Comments",
            "News.Comments.CommentText",
            "News.Comments.CommentText.Required",
            "News.Comments.CommentTitle",
            "News.Comments.CommentTitle.MaxLengthValidation",
            "News.Comments.CommentTitle.Required",
            "News.Comments.CreatedOn",
            "News.Comments.LeaveYourComment",
            "News.Comments.OnlyRegisteredUsersLeaveComments",
            "News.Comments.SeeAfterApproving",
            "News.Comments.SubmitButton",
            "News.Comments.SuccessfullyAdded",
            "News.MoreInfo",
            "News.RSS",
            "News.RSS.Hint",
            "News.ViewAll",
            "PageTitle.NewsArchive",
            "Security.Permission.ContentManagement.NewsCommentsCreateEditDelete",
            "Security.Permission.ContentManagement.NewsCommentsView",
            "Security.Permission.ContentManagement.NewsCreateEditDelete",
            "Security.Permission.ContentManagement.NewsView",
            "Sitemap.News",

            //#7368
            "Admin.ContentManagement.Polls.Polls",
            "Admin.ContentManagement.Polls.Added",
            "Admin.ContentManagement.Polls.AddNew",
            "Admin.ContentManagement.Polls.Answers",
            "Admin.ContentManagement.Polls.Answers.Fields.DisplayOrder",
            "Admin.ContentManagement.Polls.Answers.Fields.DisplayOrder.Hint",
            "Admin.ContentManagement.Polls.Answers.Fields.Name",
            "Admin.ContentManagement.Polls.Answers.Fields.Name.Hint",
            "Admin.ContentManagement.Polls.Answers.Fields.Name.Required",
            "Admin.ContentManagement.Polls.Answers.Fields.NumberOfVotes",
            "Admin.ContentManagement.Polls.Answers.SaveBeforeEdit",
            "Admin.ContentManagement.Polls.BackToList",
            "Admin.ContentManagement.Polls.Configuration.Enabled",
            "Admin.ContentManagement.Polls.Configuration.Enabled.Hint",
            "Admin.ContentManagement.Polls.Deleted",
            "Admin.ContentManagement.Polls.EditPollDetails",
            "Admin.ContentManagement.Polls.Fields.AllowGuestsToVote",
            "Admin.ContentManagement.Polls.Fields.AllowGuestsToVote.Hint",
            "Admin.ContentManagement.Polls.Fields.DisplayOrder",
            "Admin.ContentManagement.Polls.Fields.DisplayOrder.Hint",
            "Admin.ContentManagement.Polls.Fields.EndDate",
            "Admin.ContentManagement.Polls.Fields.EndDate.Hint",
            "Admin.ContentManagement.Polls.Fields.Language",
            "Admin.ContentManagement.Polls.Fields.Language.Hint",
            "Admin.ContentManagement.Polls.Fields.LimitedToStores",
            "Admin.ContentManagement.Polls.Fields.LimitedToStores.Hint",
            "Admin.ContentManagement.Polls.Fields.Name",
            "Admin.ContentManagement.Polls.Fields.Name.Hint",
            "Admin.ContentManagement.Polls.Fields.Name.Required",
            "Admin.ContentManagement.Polls.Fields.Published",
            "Admin.ContentManagement.Polls.Fields.Published.Hint",
            "Admin.ContentManagement.Polls.Fields.ShowOnHomepage",
            "Admin.ContentManagement.Polls.Fields.ShowOnHomepage.Hint",
            "Admin.ContentManagement.Polls.Fields.ShowInLeftSideColumn",
            "Admin.ContentManagement.Polls.Fields.ShowInLeftSideColumn.Hint",
            "Admin.ContentManagement.Polls.Fields.StartDate",
            "Admin.ContentManagement.Polls.Fields.StartDate.Hint",
            "Admin.ContentManagement.Polls.Info",
            "Admin.ContentManagement.Polls.List.SearchStore",
            "Admin.ContentManagement.Polls.List.SearchStore.Hint",
            "Admin.ContentManagement.Polls.Updated",
            "Admin.Documentation.Reference.Polls",
            "Polls.OnlyRegisteredUsersVote",
            "Polls.SelectAnswer",
            "Polls.Title",
            "Polls.TotalVotes",
            "Polls.Vote",
            "Polls.VotesResultLine",
            "Security.Permission.ContentManagement.PollsCreateEditDelete",
            "Security.Permission.ContentManagement.PollsView",
            "Account.ForumSubscriptions",
            "Account.ForumSubscriptions.DeleteSelected",
            "Account.ForumSubscriptions.Description",
            "Account.ForumSubscriptions.InfoColumn",
            "Account.ForumSubscriptions.NoSubscriptions",

            //#7336
            "Admin.Configuration.Settings.Forums",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsFeedCount",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsFeedCount.Hint",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsFeedEnabled",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsFeedEnabled.Hint",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsPageSize",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsPageSize.Hint",
            "Admin.Configuration.Settings.Forums.AllowCustomersToDeletePosts",
            "Admin.Configuration.Settings.Forums.AllowCustomersToDeletePosts.Hint",
            "Admin.Configuration.Settings.Forums.AllowCustomersToEditPosts",
            "Admin.Configuration.Settings.Forums.AllowCustomersToEditPosts.Hint",
            "Admin.Configuration.Settings.Forums.AllowCustomersToManageSubscriptions",
            "Admin.Configuration.Settings.Forums.AllowCustomersToManageSubscriptions.Hint",
            "Admin.Configuration.Settings.Forums.AllowGuestsToCreatePosts",
            "Admin.Configuration.Settings.Forums.AllowGuestsToCreatePosts.Hint",
            "Admin.Configuration.Settings.Forums.AllowGuestsToCreateTopics",
            "Admin.Configuration.Settings.Forums.AllowGuestsToCreateTopics.Hint",
            "Admin.Configuration.Settings.Forums.AllowPostVoting",
            "Admin.Configuration.Settings.Forums.AllowPostVoting.Hint",
            "Admin.Configuration.Settings.Forums.BlockTitle.Common",
            "Admin.Configuration.Settings.Forums.BlockTitle.Feeds",
            "Admin.Configuration.Settings.Forums.BlockTitle.PageSizes",
            "Admin.Configuration.Settings.Forums.BlockTitle.Permissions",
            "Admin.Configuration.Settings.Forums.ForumEditor",
            "Admin.Configuration.Settings.Forums.ForumEditor.Hint",
            "Admin.Configuration.Settings.Forums.ForumFeedCount",
            "Admin.Configuration.Settings.Forums.ForumFeedCount.Hint",
            "Admin.Configuration.Settings.Forums.ForumFeedsEnabled",
            "Admin.Configuration.Settings.Forums.ForumFeedsEnabled.Hint",
            "Admin.Configuration.Settings.Forums.ForumsEnabled",
            "Admin.Configuration.Settings.Forums.ForumsEnabled.Hint",
            "Admin.Configuration.Settings.Forums.MaxVotesPerDay",
            "Admin.Configuration.Settings.Forums.MaxVotesPerDay.Hint",
            "Admin.Configuration.Settings.Forums.PostsPageSize",
            "Admin.Configuration.Settings.Forums.PostsPageSize.Hint",
            "Admin.Configuration.Settings.Forums.RelativeDateTimeFormattingEnabled",
            "Admin.Configuration.Settings.Forums.RelativeDateTimeFormattingEnabled.Hint",
            "Admin.Configuration.Settings.Forums.SearchResultsPageSize",
            "Admin.Configuration.Settings.Forums.SearchResultsPageSize.Hint",
            "Admin.Configuration.Settings.Forums.ShowCustomersPostCount",
            "Admin.Configuration.Settings.Forums.ShowCustomersPostCount.Hint",
            "Admin.Configuration.Settings.Forums.SignaturesEnabled",
            "Admin.Configuration.Settings.Forums.SignaturesEnabled.Hint",
            "Admin.Configuration.Settings.Forums.TopicsPageSize",
            "Admin.Configuration.Settings.Forums.TopicsPageSize.Hint",
            "Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnForum",
            "Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnForum.Hint",
            "Admin.ContentManagement.Forums",
            "Admin.ContentManagement.Forums.Forum",
            "Admin.ContentManagement.Forums.Forum.Added",
            "Admin.ContentManagement.Forums.Forum.BackToList",
            "Admin.ContentManagement.Forums.Forum.CreateForum",
            "Admin.ContentManagement.Forums.Forum.Deleted",
            "Admin.ContentManagement.Forums.Forum.EditForum",
            "Admin.ContentManagement.Forums.Forum.Fields.CreatedOn",
            "Admin.ContentManagement.Forums.Forum.Fields.Description",
            "Admin.ContentManagement.Forums.Forum.Fields.Description.Hint",
            "Admin.ContentManagement.Forums.Forum.Fields.DisplayOrder",
            "Admin.ContentManagement.Forums.Forum.Fields.DisplayOrder.Hint",
            "Admin.ContentManagement.Forums.Forum.Fields.ForumGroupId",
            "Admin.ContentManagement.Forums.Forum.Fields.ForumGroupId.Hint",
            "Admin.ContentManagement.Forums.Forum.Fields.ForumGroupId.Required",
            "Admin.ContentManagement.Forums.Forum.Fields.Name",
            "Admin.ContentManagement.Forums.Forum.Fields.Name.Hint",
            "Admin.ContentManagement.Forums.Forum.Fields.Name.Required",
            "Admin.ContentManagement.Forums.Forum.Updated",
            "Admin.ContentManagement.Forums.ForumGroup",
            "Admin.ContentManagement.Forums.ForumGroup.Added",
            "Admin.ContentManagement.Forums.ForumGroup.BackToList",
            "Admin.ContentManagement.Forums.ForumGroup.CreateForumGroup",
            "Admin.ContentManagement.Forums.ForumGroup.Deleted",
            "Admin.ContentManagement.Forums.ForumGroup.EditForumGroup",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.CreatedOn",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.DisplayOrder",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.DisplayOrder.Hint",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.Name",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.Name.Hint",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.Name.Required",
            "Admin.ContentManagement.Forums.ForumGroup.Updated",

            "Admin.Documentation.Reference.Forums",

            "Enums.Nop.Core.Domain.Forums.EditorType.BBCodeEditor",
            "Enums.Nop.Core.Domain.Forums.EditorType.HtmlEditor",
            "Enums.Nop.Core.Domain.Forums.EditorType.MarkdownEditor",
            "Enums.Nop.Core.Domain.Forums.EditorType.SimpleTextBox",
            "Enums.Nop.Core.Domain.Forums.ForumSearchType.All",
            "Enums.Nop.Core.Domain.Forums.ForumSearchType.PostTextOnly",
            "Enums.Nop.Core.Domain.Forums.ForumSearchType.TopicTitlesOnly",
            "Enums.Nop.Core.Domain.Forums.ForumTopicType.Announcement",
            "Enums.Nop.Core.Domain.Forums.ForumTopicType.Normal",
            "Enums.Nop.Core.Domain.Forums.ForumTopicType.Sticky",

            "Forum.ActiveDiscussions",
            "Forum.ActiveDiscussions.ViewAll",
            "Forum.ActiveDiscussionsFeedDescription",
            "Forum.ActiveDiscussionsFeedTitle",
            "Forum.ActiveDiscussionsRSSLinkTitle",
            "Forum.AdvancedSearch",
            "Forum.Announcement",
            "Forum.Author",
            "Forum.Breadcrumb.ForumGroupTitle",
            "Forum.Breadcrumb.ForumHomeTitle",
            "Forum.Breadcrumb.ForumTitle",
            "Forum.Breadcrumb.HomeTitle",
            "Forum.Breadcrumb.TopicTitle",
            "Forum.By",
            "Forum.Cancel",
            "Forum.DeletePost",
            "Forum.DeleteTopic",
            "Forum.EditPost",
            "Forum.EditTopic",
            "Forum.Forum",
            "Forum.ForumFeedDescription",
            "Forum.ForumFeedTitle",
            "Forum.ForumName",
            "Forum.ForumRSSLinkTitle",
            "Forum.Forums",
            "Forum.Home",
            "Forum.In",
            "Forum.Joined",
            "Forum.LatestPost",
            "Forum.Location",
            "Forum.Moderator",
            "Forum.MoveTopic",
            "Forum.NewPost",
            "Forum.NewTopic",
            "Forum.NoPosts",
            "Forum.Normal",
            "Forum.NotifyWhenSomeonePostsInThisTopic",
            "Forum.PageTitle.ActiveDiscussions",
            "Forum.PageTitle.Default",
            "Forum.PageTitle.MoveTopic",
            "Forum.PageTitle.PostEdit",
            "Forum.PageTitle.PostNew",
            "Forum.PageTitle.Search",
            "Forum.PageTitle.TopicEdit",
            "Forum.PageTitle.TopicNew",
            "Forum.Post.IsNotUseful",
            "Forum.Post.IsUseful",
            "Forum.Post.Text",
            "Forum.Posted",
            "Forum.PostLinkTitle",
            "Forum.Posts",
            "Forum.Priority",
            "Forum.PrivateMessages.PM",
            "Forum.QuotePost",
            "Forum.Replies",
            "Forum.Reply",
            "Forum.RSS",
            "Forum.Search",
            "Forum.Search.AdvancedSearch",
            "Forum.Search.LimitResultsToPrevious",
            "Forum.Search.LimitResultsToPrevious.1day",
            "Forum.Search.LimitResultsToPrevious.1month",
            "Forum.Search.LimitResultsToPrevious.1year",
            "Forum.Search.LimitResultsToPrevious.2weeks",
            "Forum.Search.LimitResultsToPrevious.3months",
            "Forum.Search.LimitResultsToPrevious.6months",
            "Forum.Search.LimitResultsToPrevious.7days",
            "Forum.Search.LimitResultsToPrevious.AllResults",
            "Forum.Search.SearchInForum",
            "Forum.Search.SearchInForum.All",
            "Forum.Search.SearchKeyword",
            "Forum.Search.SearchWithin",
            "Forum.Search.SearchWithin.All",
            "Forum.Search.SearchWithin.PostTextOnly",
            "Forum.Search.SearchWithin.TopicTitlesOnly",
            "Forum.SearchButton",
            "Forum.SearchForumsTooltip",
            "Forum.SearchNoResultsText",
            "Forum.SearchTermMinimumLengthIsNCharacters",
            "Forum.SelectTheForumToMoveTopic",
            "Forum.Status",
            "Forum.Sticky",
            "Forum.Submit",
            "Forum.TextCannotBeEmpty",
            "Forum.Topics",
            "Forum.Topics.GotoPostPager",
            "Forum.TopicSubjectCannotBeEmpty",
            "Forum.TopicTitle",
            "Forum.TruncatePostfix",
            "Forum.TotalPosts",
            "Forum.UnwatchForum",
            "Forum.UnwatchTopic",
            "Forum.Views",
            "Forum.Votes",
            "Forum.Votes.AlreadyVoted",
            "Forum.Votes.Login",
            "Forum.Votes.MaxVotesReached",
            "Forum.Votes.OwnPost",
            "Forum.WatchForum",
            "Forum.WatchTopic",

            "MarkdownEditor.TabWrite",
            "MarkdownEditor.TabPreview",

            "Literals.Nop.Core.Http.NopRouteNames.General.Boards",
            "PageTitle.ForumSubscriptions",

            "Security.Permission.ContentManagement.ForumsCreateEditDelete",
            "Security.Permission.ContentManagement.ForumsView",

            "Profile.LatestPosts",
            "Profile.LatestPosts.NoPosts",
            "Profile.PersonalInfo",

            //#8131
            "Account.Login.WrongCredentials.CustomerNotExist",
            "Account.Login.WrongCredentials.NotRegistered",
            "Account.PasswordRecovery.EmailHasBeenSent",
            "Account.PasswordRecovery.EmailNotFound",

            //#8093
            "Admin.Configuration.Settings.CustomerSettings.PhoneNumberRegexValidationRule.Error",
            "Admin.Configuration.Settings.CustomerUser.PhoneNumberValidationRule",
            "Admin.Configuration.Settings.CustomerUser.PhoneNumberValidationRule.Hint",
            "Admin.Configuration.Settings.CustomerUser.PhoneNumberValidationUseRegex",
            "Admin.Configuration.Settings.CustomerUser.PhoneNumberValidationUseRegex.Hint",

            //#8169
            "Admin.Orders.Fields.CardCVV2",
            "Admin.Orders.Fields.CardCVV2.Hint",
            "Admin.Orders.Fields.CardExpirationMonth",
            "Admin.Orders.Fields.CardExpirationMonth.Hint",
            "Admin.Orders.Fields.CardExpirationYear",
            "Admin.Orders.Fields.CardExpirationYear.Hint",
            "Admin.Orders.Fields.CardName",
            "Admin.Orders.Fields.CardName.Hint",
            "Admin.Orders.Fields.CardNumber",
            "Admin.Orders.Fields.CardNumber.Hint",
            "Admin.Orders.Fields.CardType",
            "Admin.Orders.Fields.CardType.Hint",
            "Payment.CardCode",
            "Payment.CardCode.Required",
            "Payment.CardCode.Wrong",
            "Payment.CardholderName",
            "Payment.CardholderName.Required",
            "Payment.CardNumber",
            "Payment.CardNumber.Required",
            "Payment.CardNumber.Wrong",
            "Payment.ExpirationDate",
            "Payment.ExpirationDate.Expired",
            "Payment.ExpireMonth.Required",
            "Payment.ExpireYear.Required",
            "Payment.SelectCreditCard",
        });

        #endregion

        #region Rename locales

        this.RenameLocales(new Dictionary<string, string>
        {
            ["Admin.Configuration.Settings.Forums.AllowPrivateMessages"] = "Admin.Configuration.Settings.CustomerUser.AllowPrivateMessages",
            ["Admin.Configuration.Settings.Forums.AllowPrivateMessages.Hint"] = "Admin.Configuration.Settings.CustomerUser.AllowPrivateMessages.Hint",
            ["Admin.Configuration.Settings.Forums.ShowAlertForPM"] = "Admin.Configuration.Settings.CustomerUser.ShowAlertForPM",
            ["Admin.Configuration.Settings.Forums.ShowAlertForPM.Hint"] = "Admin.Configuration.Settings.CustomerUser.ShowAlertForPM.Hint",
            ["Admin.Configuration.Settings.Forums.NotifyAboutPrivateMessages"] = "Admin.Configuration.Settings.CustomerUser.NotifyAboutPrivateMessages",
            ["Admin.Configuration.Settings.Forums.NotifyAboutPrivateMessages.Hint"] = "Admin.Configuration.Settings.CustomerUser.NotifyAboutPrivateMessages.Hint",

            //#8097
            ["Admin.Configuration.Settings.GeneralCommon.TwitterLink"] = "Admin.Configuration.Settings.GeneralCommon.XLink",
            ["Admin.Configuration.Settings.GeneralCommon.TwitterLink.Hint"] = "Admin.Configuration.Settings.GeneralCommon.XLink.Hint",
            ["Footer.FollowUs.Twitter"] = "Footer.FollowUs.X",
        });

        #endregion

        #region Add or update locales

        this.AddOrUpdateLocaleResource(new Dictionary<string, string>
        {
            //#7898
            ["Admin.Configuration.Settings.Catalog.ArtificialIntelligence.LogRequests"] = "Log AI requests",
            ["Admin.Configuration.Settings.Catalog.ArtificialIntelligence.LogRequests.Hint"] = "Check to enable logging of all requests to AI services.",

            //#7989
            ["Products.ProductHasBeenUpdatedInTheWishlist.Link"] = "The product has been updated in your <a href=\"{0}\">wishlist</a>",

            //#8021
            ["Admin.Catalog.Products.RelatedProducts.CyclicallyRelated"] = "Circular dependency is not allowed for required products (e.g. product A requires product B. And product B requires product A)",

            //#7743
            ["Admin.Promotions.Reminder.AbandonedCartEnabled"] = "Abandoned cart reminders enabled",
            ["Admin.Promotions.Reminder.AbandonedCartEnabled.Hint"] = "Check to enable Abandoned cart reminders.",
            ["Admin.Promotions.Reminder.FollowUp.DelayBeforeSend"] = "Delay send",
            ["Admin.Promotions.Reminder.FollowUp.DelayBeforeSend.Hint"] = "A delay before sending the follow up.",
            ["Admin.Promotions.Reminder.FollowUp.DelayBeforeSend.MustBeGreaterThanZero"] = "The delay must be greater than '0'.",
            ["Admin.Promotions.Reminder.FollowUp.DelayBeforeSend.Required"] = "The delay is required.",
            ["Admin.Promotions.Reminder.FollowUp.Enabled"] = "Follow up #{0}",
            ["Admin.Promotions.Reminder.FollowUp.Enabled.Hint"] = "Check to enable reminder.",
            ["Admin.Promotions.Reminder.IncompleteRegistrationEnabled"] = "Incomplete registration reminder enabled",
            ["Admin.Promotions.Reminder.IncompleteRegistrationEnabled.Hint"] = "Check to enable incomplete registration reminders.",
            ["Admin.Promotions.Reminder.PendingOrdersEnabled"] = "Pending orders reminders enabled",
            ["Admin.Promotions.Reminder.PendingOrdersEnabled.Hint"] = "Check to enable pending orders reminders.",
            ["Admin.Promotions.Reminders"] = "Reminders",
            ["Admin.Promotions.Reminders.Warning.TaskDisabled"] = "Please remember <a href=\"{0}\" target=\"_blank\">to enable</a> the \"{1}\" scheduled task.",
            ["Admin.Promotions.Reminders.Warning.MultiStore"] = "Abandoned cart reminders may not work as expected when using a multi-store setup.",
            ["Admin.Promotions.Reminders.Warning.NotFound"] = "The scheduled task not found.",
            [$"Admin.ContentManagement.MessageTemplates.Description.{MessageTemplateSystemNames.REMINDER_ABANDONED_CART_FOLLOW_UP_1_MESSAGE}"] = "This message template is used to send the follow-up #1 for a abandoned cart.",
            [$"Admin.ContentManagement.MessageTemplates.Description.{MessageTemplateSystemNames.REMINDER_ABANDONED_CART_FOLLOW_UP_2_MESSAGE}"] = "This message template is used to send the follow-up #2 for a abandoned cart.",
            [$"Admin.ContentManagement.MessageTemplates.Description.{MessageTemplateSystemNames.REMINDER_ABANDONED_CART_FOLLOW_UP_3_MESSAGE}"] = "This message template is used to send the follow-up #3 for a abandoned cart.",
            [$"Admin.ContentManagement.MessageTemplates.Description.{MessageTemplateSystemNames.REMINDER_PENDING_ORDER_FOLLOW_UP_1_MESSAGE}"] = "This message template is used to send the follow-up #1 for a pending order.",
            [$"Admin.ContentManagement.MessageTemplates.Description.{MessageTemplateSystemNames.REMINDER_PENDING_ORDER_FOLLOW_UP_2_MESSAGE}"] = "This message template is used to send the follow-up #2 for a pending order.",
            [$"Admin.ContentManagement.MessageTemplates.Description.{MessageTemplateSystemNames.REMINDER_REGISTRATION_FOLLOW_UP_MESSAGE}"] = "This message template is used to send the follow-up #1 for a incomplete registration.",

            //#7906
            ["Wishlist.DuplicateName"] = "A wishlist with this name already exists.",

            //#7907
            ["Wishlist.RenameCustomWishlist"] = "Rename wishlist",

            //#7336
            ["Admin.ContentManagement.MessageTemplates.Description.Customer.NewPM"] = "This message template is used when the customer gets a notification about a new private message being received. You can set up this option by ticking the checkbox <strong>Show alert for PM</strong> in Configuration - Settings - Customer settings.",
            ["Admin.Configuration.Settings.CustomerUser.BlockTitle.PrivateMessage"] = "Private messages",

            //#8125
            ["Admin.Configuration.Settings.Catalog.ShowCategoryProductNumber"] = "Show the number of products next to each category",
            ["Admin.Configuration.Settings.Catalog.ShowCategoryProductNumber.Hint"] = "Check to show the number of products next to each category (category navigation block).",
            ["Admin.Configuration.Settings.Catalog.ShowCategoryProductNumberIncludingSubcategories"] = "Include subcategories (number of products)",
            ["Admin.Configuration.Settings.Catalog.ShowCategoryProductNumberIncludingSubcategories.Hint"] = "Check to include subcategories when showing the number of products next to each category.",

            //#7386
            ["Admin.Configuration.Settings.Shipping.AllowCustomerToChooseDeliveryDate"] = "Allow customers to choose delivery date",
            ["Admin.Configuration.Settings.Shipping.AllowCustomerToChooseDeliveryDate.Hint"] = "Enables customers to select their preferred delivery date during checkout. This option is available only when the selected shipping method has a defined TransitDays value.",
            ["Admin.Configuration.Settings.Shipping.DeliveryDateRangeDays"] = "Range of days to choose from",
            ["Admin.Configuration.Settings.Shipping.DeliveryDateRangeDays.Hint"] = "Specifies how many delivery date options will be available to customers, starting from the earliest possible delivery date calculated using TransitDays.",
            ["Checkout.SelectDesiredDeliveryDate"] = "Select desired delivery date",
            ["Admin.Orders.Fields.DesiredDeliveryDate"] = "Desired delivery date",
            ["Admin.Orders.Fields.DesiredDeliveryDate.Hint"] = "The delivery date selected by the customer during checkout.",
            ["Order.Shipping.DesiredDeliveryDate"] = "Desired delivery date",

            //#8097
            ["Admin.Configuration.Settings.GeneralCommon.XLink"] = "X page URL",
            ["Admin.Configuration.Settings.GeneralCommon.XLink.Hint"] = "Specify your X page URL. Leave empty if you have no such page.",
            ["Footer.FollowUs.X"] = "X",

            //#8073
            ["Admin.System.SystemInfo.NopLatestVersion"] = "Latest nopCommerce version",
            ["Admin.System.SystemInfo.NopLatestVersion.Hint"] = "The latest nopCommerce version, available for download.",
            ["Admin.System.SystemInfo.NopLatestVersion.Text"] = "<a href='{1}' target='_blank'>{0}</a> (see the <a href='{2}' target='_blank'>release-notes</a>)",

            //#8136
            ["Footer.FollowUs.TikTok"] = "TikTok",
            ["Footer.FollowUs.Snapchat"] = "Snapchat",
            ["Footer.FollowUs.Pinterest"] = "Pinterest",
            ["Footer.FollowUs.Tumblr"] = "Tumblr",
            ["Admin.Configuration.Settings.GeneralCommon.TikTokLink"] = "TikTok URL",
            ["Admin.Configuration.Settings.GeneralCommon.TikTokLink.Hint"] = "Specify your TikTok page URL. Leave empty if you have no such page.",
            ["Admin.Configuration.Settings.GeneralCommon.SnapchatLink"] = "Snapchat URL",
            ["Admin.Configuration.Settings.GeneralCommon.SnapchatLink.Hint"] = "Specify your Snapchat page URL. Leave empty if you have no such page.",
            ["Admin.Configuration.Settings.GeneralCommon.PinterestLink"] = "Pinterest URL",
            ["Admin.Configuration.Settings.GeneralCommon.PinterestLink.Hint"] = "Specify your Pinterest page URL. Leave empty if you have no such page.",
            ["Admin.Configuration.Settings.GeneralCommon.TumblrLink"] = "Tumblr URL",
            ["Admin.Configuration.Settings.GeneralCommon.TumblrLink.Hint"] = "Specify your Tumblr page URL. Leave empty if you have no such page.",

            //#8131
            ["Account.PasswordRecovery.SendEmailMessage"] = "If there is an account associated with {0}, you will receive an email with a link to reset your password.",

            //#8128
            ["Admin.Configuration.AppSettings.Data.BulkCopyWithCheckConstraints"] = "Check constraints during bulk copy operations",
            ["Admin.Configuration.AppSettings.Data.BulkCopyWithCheckConstraints.Hint"] = "Check to validate data inserted by bulk copy operations against the check constraints defined in the target table. Uncheck to improve performance, but be aware that it can result in data that does not meet the table's integrity requirements.",

            //#8117
            ["Admin.Configuration.AppSettings.Data.CloseDataContextAfterUse"] = "Close dataContext after use",
            ["Admin.Configuration.AppSettings.Data.CloseDataContextAfterUse.Hint"] = "Check to automatically dispose the data context after each operation, which helps prevent resource leaks. Uncheck if you need to keep the data context open for multiple sequential operations.",

            //#8069
            ["Admin.Configuration.Settings.Catalog.ShowSearchTermHistory"] = "Show the term history",
            ["Admin.Configuration.Settings.Catalog.ShowSearchTermHistory.Hint"] = "Show the search term history in the autocomplete list of the search box.",
            ["Admin.Configuration.Settings.Catalog.NumberOfSearchTermHistoryItems"] = "Max number of term history items",
            ["Admin.Configuration.Settings.Catalog.NumberOfSearchTermHistoryItems.Hint"] = "The maximum number of search term history items to display.",
            ["Admin.System.Maintenance.ClearSearchHistory"] = "Clear search history",
            ["Admin.System.Maintenance.ClearSearchHistory.Button"] = "Clear",
            ["Admin.System.Maintenance.ClearSearchHistory.Progress"] = "Clearing...",
            ["Admin.System.Maintenance.ClearSearchHistory.Text"] = "Delete search history data from the database.",
            ["Admin.System.Maintenance.ClearSearchHistory.Complete"] = "Clearing search history data completed",
            ["Admin.System.Maintenance.ClearSearchHistory.TotalDeleted"] = "{0} items were deleted",

            //#8120
            ["Admin.Configuration.Settings.Order.AutoCancelEnabled"] = "Enable auto-canceling of unpaid orders",
            ["Admin.Configuration.Settings.Order.AutoCancelEnabled.Hint"] = "Check this option to enable automatic cancellation of unpaid orders.",
            ["Admin.Configuration.Settings.Order.AutoCancelDelay"] = "Auto-cancel delay",
            ["Admin.Configuration.Settings.Order.AutoCancelDelay.Hint"] = "Enter the delay (in minutes) after order placement before unpaid orders are canceled.",
            ["Admin.Configuration.Settings.Order.AutoCancelIgnoredPaymentMethods"] = "Excluded payment methods",
            ["Admin.Configuration.Settings.Order.AutoCancelIgnoredPaymentMethods.Hint"] = "Select payment methods excluded from automatic cancellation of unpaid orders.",
            ["Admin.Configuration.Settings.Order.AutoCancelRestoreShoppingCart"] = "Put order back as shopping cart",
            ["Admin.Configuration.Settings.Order.AutoCancelRestoreShoppingCart.Hint"] = "Check this option to add auto-canceled orders back to the shopping cart.",
            ["Admin.Configuration.Settings.Order.Warning.NotFound"] = "Auto-cancel unpaid orders task not found",
            ["Admin.Configuration.Settings.Order.Warning.TaskDisabled"] = "Please remember <a href=\"{0}\" target=\"_blank\">to enable</a> the \"{1}\" scheduled task.",

            //#1832
            ["ActivityLog.AddNewContactFormAttribute"] = "Added a new contact form attribute (ID = {0})",
            ["ActivityLog.AddNewContactFormAttributeValue"] = "Added a new contact form attribute value (ID = {0})",
            ["ActivityLog.DeleteContactFormAttribute"] = "Deleted a contact form attribute (ID = {0})",
            ["ActivityLog.DeleteContactFormAttributeValue"] = "Deleted a contact form attribute value (ID = {0})",
            ["ActivityLog.EditContactFormAttribute"] = "Edited a contact form attribute (ID = {0})",
            ["ActivityLog.EditContactFormAttributeValue"] = "Edited a contact form attribute value (ID = {0})",
            ["Admin.Configuration.Settings.GeneralCommon.BlockTitle.ContactForm"] = "Contact form",
            ["Admin.Common.ContactFormAttributes"] = "Custom contact form attributes",
            ["Admin.Common.ContactFormAttributes.Added"] = "The new attribute has been added successfully.",
            ["Admin.Common.ContactFormAttributes.AddNew"] = "Add a new contact form attribute",
            ["Admin.Common.ContactFormAttributes.BackToList"] = "back to settings",
            ["Admin.Common.ContactFormAttributes.Deleted"] = "The attribute has been deleted successfully.",
            ["Admin.Common.ContactFormAttributes.Description"] = "If the default form fields are not enough for your needs, then you can manage additional contact form attributes below.",
            ["Admin.Common.ContactFormAttributes.EditAttributeDetails"] = "Edit contact form attribute details",
            ["Admin.Common.ContactFormAttributes.Fields.AttributeControlType"] = "Control type",
            ["Admin.Common.ContactFormAttributes.Fields.AttributeControlType.Hint"] = "Choose how to display your attribute values.",
            ["Admin.Common.ContactFormAttributes.Fields.DisplayOrder"] = "Display order",
            ["Admin.Common.ContactFormAttributes.Fields.DisplayOrder.Hint"] = "The contact form attribute display order. 1 represents the first item in the list.",
            ["Admin.Common.ContactFormAttributes.Fields.IsRequired"] = "Required",
            ["Admin.Common.ContactFormAttributes.Fields.IsRequired.Hint"] = "When an attribute is required, the customer must choose an appropriate attribute value before they can send form.",
            ["Admin.Common.ContactFormAttributes.Fields.Name"] = "Name",
            ["Admin.Common.ContactFormAttributes.Fields.Name.Hint"] = "The name of the contact form attribute.",
            ["Admin.Common.ContactFormAttributes.Fields.Name.Required"] = "Please provide a name.",
            ["Admin.Common.ContactFormAttributes.Info"] = "Attribute info",
            ["Admin.Common.ContactFormAttributes.Values"] = "Attribute values",
            ["Admin.Common.ContactFormAttributes.Values.AddNew"] = "Add a new attribute value",
            ["Admin.Common.ContactFormAttributes.Values.EditValueDetails"] = "Edit contact form value details",
            ["Admin.Common.ContactFormAttributes.Values.Fields.Name"] = "Name",
            ["Admin.Common.ContactFormAttributes.Values.Fields.Name.Hint"] = "The name of the contact form attribute.",
            ["Admin.Common.ContactFormAttributes.Values.Fields.Name.Required"] = "Please provide a name.",
            ["Admin.Common.ContactFormAttributes.Values.Fields.DisplayOrder"] = "Display order",
            ["Admin.Common.ContactFormAttributes.Values.Fields.DisplayOrder.Hint"] = "The display order of the attribute value. 1 represents the first item in attribute value list.",
            ["Admin.Common.ContactFormAttributes.Values.Fields.IsPreSelected"] = "Pre-selected",
            ["Admin.Common.ContactFormAttributes.Values.Fields.IsPreSelected.Hint"] = "Determines whether this attribute value is pre-selected.",
            ["Admin.Common.ContactFormAttributes.Values.SaveBeforeEdit"] = "You need to save the contact form attribute before you can add values for this contact form attribute page.",
            ["Admin.Common.ContactFormAttributes.Updated"] = "The attribute has been updated successfully.",
            ["ContactUs.SelectAttribute"] = "Please select {0}",

            //#2430
            ["Admin.Customers.Customers.Fields.PhoneSmsVerified"] = "Is phone verified",
            ["Admin.Customers.Customers.Fields.PhoneSmsVerified.Hint"] = "Indicates whether the customer's phone number has been verified via SMS.",

            ["Admin.Configuration.Settings.CustomerUser.LoginByPhoneEnabled"] = "'Login by phone' enabled",
            ["Admin.Configuration.Settings.CustomerUser.LoginByPhoneEnabled.Hint"] = "Check if 'Login by phone' is enabled.",
            ["Admin.Configuration.Settings.CustomerUser.OtpTimeLife"] = "OTP code time to live",
            ["Admin.Configuration.Settings.CustomerUser.OtpTimeLife.Hint"] = "The time (in seconds) during which the OTP code is valid.",
            ["Admin.Configuration.Settings.CustomerUser.OtpCountAttemptsToSendCode"] = "OTP code send attempts",
            ["Admin.Configuration.Settings.CustomerUser.OtpCountAttemptsToSendCode.Hint"] = "The number of attempts to send the OTP code.",
            ["Admin.Configuration.Settings.CustomerUser.OtpTimeToRepeat"] = "OTP code resend time",
            ["Admin.Configuration.Settings.CustomerUser.OtpTimeToRepeat.Hint"] = "The time (in minutes) before the OTP code can be resent.",
            ["Admin.Configuration.Settings.CustomerUser.OtpLength"] = "OTP code length",
            ["Admin.Configuration.Settings.CustomerUser.OtpLength.Hint"] = "The length of the OTP code.",

            ["Admin.Configuration.Settings.CustomerUser.LoginByPhoneEnabled.Warning"] = "Warning - Login by Phone requires the following prerequisites: \"'Phone number' enabled\", \"'Phone number' required\", and \"Phone number validation is enabled\" on the <a href=\"{0}\">Customer settings</a> page. Please configure these settings accordingly.",
            ["Account.Login.Fields.Phone"] = "Phone",
            ["Account.Login.EmailMode"] = "Login with email",
            ["Account.Login.PhoneMode"] = "Login with phone",
            ["Account.Login.Phone.NotEnabled"] = "Phone login is not enabled.",

            // Phone verification
            ["PageTitle.ChangePhone"] = "Change phone number",
            ["PageTitle.RegisterOtp"] = "Phone number verification",
            ["PageTitle.LoginOtp"] = "Phone number verification",

            ["Account.IsAlreadyExistsVerifiedPhoneNumber"] = "A customer with the specified verified phone number already exists.",
            ["Account.Register.OtpRegisterSmsText"] = "We'll send you a code via SMS to complete registration.",
            ["Account.OtpPhoneVerification.OtpUpdatePhoneSmsText"] = "We'll send you a code via SMS to confirm changing your phone number.",
            ["Account.Login.OtpLoginSmsText"] = "We'll send you a code via SMS to confirm your login.",

            ["PhoneVerification.SendSms"] = "Send SMS",
            ["PhoneVerification.OtpCodeExpires"] = "Code expires in",
            ["PhoneVerification.Fields.OtpCode"] = "SMS code",
            ["PhoneVerification.Fields.Phone"] = "Phone",
            ["PhoneVerification.OtpCode.Required"] = "SMS code is required.",
            ["PhoneVerification.OtpCode.Message"] = "Your OTP code is: {0}",
            ["PhoneVerification.OtpCode.Error.AttemptLimit"] = "Attempt limit exceeded. Try again in {0} minutes.",
            ["PhoneVerification.OtpCode.Error.RecentlySent"] = "The code has already been sent. Please wait {0} seconds.",
            ["PhoneVerification.OtpCode.Error.SendError"] = "Failed to send SMS code. Please try again.",
            ["PhoneVerification.OtpCode.Error.NotRequested"] = "You have not requested an SMS code. Please request a code and try again.",
            ["PhoneVerification.OtpCode.Error.Expired"] = "The SMS code has expired.",
            ["PhoneVerification.OtpCode.Error.Invalid"] = "The SMS code you entered is invalid. Please try again.",
            ["PhoneVerification.OtpCode.Error.Verification"] = "SMS verification error.",
            ["PhoneVerification.Placeholder"] = "+1 (555) 000-0000",

            //menu
            ["Admin.Configuration.Sms.Providers"] = "Sms providers",
            ["Admin.Configuration.Sms.Providers.BackToList"] = "back to sms provider list",
            ["Admin.Configuration.Sms.Providers.Configure"] = "Configure",
            ["Admin.Configuration.Sms.Providers.Fields.FriendlyName"] = "Friendly name",
            ["Admin.Configuration.Sms.Providers.Fields.IsPrimaryProvider"] = "Is primary provider",
            ["Admin.Configuration.Sms.Providers.Fields.MarkAsPrimaryProvider"] = "Mark as primary provider",
            ["Admin.Configuration.Sms.Providers.Fields.SystemName"] = "System name",
            ["Admin.Documentation.Reference.SmsProviders"] = "Learn more about <a target=\"_blank\" href=\"{0}\">sms providers</a>.",

            //customer info
            ["Account.CustomerInfo.VerifyPhoneNumber"] = "Verify phone number",
            ["Account.Fields.Phone.Status.NotVerified"] = "Phone number is not verified",

            //#4279
            ["Admin.Catalog.Products.Multimedia.Object3d"] = "3D model",
            ["Admin.Catalog.Products.Multimedia.Object3d.Fields.FileName"] = "3D model file",
            ["Admin.Catalog.Products.Multimedia.Object3d.Fields.FileName.Hint"] = "Upload a .glb file containing a 3D model to be displayed on the product page.",
            ["Admin.Catalog.Products.Multimedia.Object3d.Fields.Preview"] = "Preview",
            ["Admin.Catalog.Products.Multimedia.Object3d.Fields.Preview.Hint"] = "Upload an image to be used as the thumbnail and displayed as a poster in the viewport until the 3D object is loaded.",
            ["Admin.Catalog.Products.Multimedia.Object3d.Fields.AltAttribute"] = "Alternative text",
            ["Admin.Catalog.Products.Multimedia.Object3d.Fields.AltAttribute.Hint"] = "The \"alt\" attribute for the \"model-viewer\" HTML element.",
            ["Admin.Catalog.Products.Multimedia.Object3d.Save"] = "Save",

            ["Admin.Configuration.Settings.Media.BlockTitle.Product3dObject"] = "Product 3D models",
            ["Admin.Configuration.Settings.Media.Object3dAutoRotateEnabled"] = "Auto-rotate",
            ["Admin.Configuration.Settings.Media.Object3dAutoRotateEnabled.Hint"] = "Check this option to enable automatic rotation of product 3D models in the viewport.",
            ["Admin.Configuration.Settings.Media.Object3dCameraControlEnabled"] = "Camera control",
            ["Admin.Configuration.Settings.Media.Object3dCameraControlEnabled.Hint"] = "Check this option to enable camera control in the viewport.",
            ["Admin.Configuration.Settings.Media.Object3dLazyLoadingEnabled"] = "Lazy loading",
            ["Admin.Configuration.Settings.Media.Object3dLazyLoadingEnabled.Hint"] = "Check this option to enable lazy loading of 3D models on the product details page.",
            ["Admin.Configuration.Settings.Media.Object3dUploadSizeLimit"] = "Upload size limit",
            ["Admin.Configuration.Settings.Media.Object3dUploadSizeLimit.Hint"] = "The maximum allowed upload size for product 3D model (in megabytes).",
            ["Admin.Configuration.Settings.Media.Object3dZoomEnabled"] = "Zoom",
            ["Admin.Configuration.Settings.Media.Object3dZoomEnabled.Hint"] = "Check this option to enable zoom functionality for product 3D models.",

            //#8098
            ["Admin.Catalog.PriceLists.Fields.Name"] = "Name",
            ["Admin.Catalog.PriceLists.Fields.Name.Hint"] = "The name of the price list.",
            ["Admin.Catalog.PriceLists.Fields.Name.Required"] = "The name of the price list is required.",
            ["Admin.Catalog.PriceLists.Fields.Description"] = "Description",
            ["Admin.Catalog.PriceLists.Fields.Description.Hint"] = "The description of the price list.",
            ["Admin.Catalog.PriceLists.Fields.Active"] = "Active",
            ["Admin.Catalog.PriceLists.Fields.Active.Hint"] = "Check to make the price list active. Inactive price lists won't be applied to products.",
            ["Admin.Catalog.PriceLists.Fields.StartDateUtc"] = "Start date",
            ["Admin.Catalog.PriceLists.Fields.StartDateUtc.Hint"] = "The date and time when the price list becomes active. Leave empty to activate immediately.",
            ["Admin.Catalog.PriceLists.Fields.EndDateUtc"] = "End date",
            ["Admin.Catalog.PriceLists.Fields.EndDateUtc.Hint"] = "The date and time when the price list expires. Leave empty to make it active indefinitely.",
            ["Admin.Catalog.PriceLists.Fields.PriceCalculationTypeId"] = "Price calculation type",
            ["Admin.Catalog.PriceLists.Fields.PriceCalculationTypeId.Hint"] = "Select the price calculation type for this price list.",
            ["Admin.Catalog.PriceLists.Fields.PriceCalculationValue"] = "Price calculation value",
            ["Admin.Catalog.PriceLists.Fields.PriceCalculationValue.Hint"] = "Specify the price calculation value. Its meaning depends on the selected price calculation type. For example, if you select 'Percentage Increase' as the price calculation type, enter the percentage discount to be applied to product prices (e.g. enter '10' to apply a 10% discount).",
            ["Admin.Catalog.PriceLists.Fields.Priority"] = "Priority",
            ["Admin.Catalog.PriceLists.Fields.Priority.Hint"] = "The priority of the price list. This field is used to determine the order in which price lists are applied to products. Price lists with higher priority values are applied after price lists with lower priority values. If two or more price lists have the same priority, they are applied in the order they were created.",
            ["Admin.Catalog.PriceLists.List.CustomerRoles"] = "Customer roles",
            ["Admin.Catalog.PriceLists.List.CustomerRoles.Hint"] = "Filter price lists by customer role. Only price lists that are applied to the selected customer role will be displayed in the list.",
            ["Admin.Catalog.PriceLists.Fields.CustomerRoles"] = "Customer roles",
            ["Admin.Catalog.PriceLists.Fields.CustomerRoles.Hint"] = "Select customer roles to which this price list will be applied. If no customer role is selected, the price list will be applied to all customers.",
            ["Admin.Catalog.PriceLists.List.SearchIsActive"] = "Active",
            ["Admin.Catalog.PriceLists.List.SearchIsActive.Hint"] = "Filter price lists by their active status. Leave empty to display all price lists.",

            ["Admin.Catalog.PriceLists"] = "Price lists",
            ["Admin.Catalog.PriceLists.AddNew"] = "Add new price list",
            ["Admin.Catalog.PriceLists.ImportFromExcelTip"] = "Imported price lists are distinguished by ID. If the ID already exists, then its corresponding price list will be updated. You should not specify ID (leave 0) for new price lists.",
            ["Admin.Documentation.Reference.PriceLists"] = "Learn more about <a target=\"_blank\" href=\"{0}\">price lists</a>",
            ["Admin.Catalog.PriceLists.NoPriceLists"] = "No price lists selected",
            ["Admin.Catalog.PriceLists.AddNew"] = "Add new price list",
            ["Admin.Catalog.PriceLists.EditPriceListDetails"] = "Edit price list",
            ["Admin.Catalog.PriceLists.BackToList"] = "back to price lists",
            ["Admin.Catalog.PriceLists.Imported"] = "Price lists have been imported successfully.",

            ["Admin.Catalog.PriceList.Info"] = "Price list info",
            ["Admin.Catalog.PriceList.Products"] = "Products",
            ["Admin.Catalog.PriceList.Customers"] = "Customers",
            ["Admin.Catalog.PriceList.Products.SaveBeforeEdit"] = "You need to save the price list before you can add products for this page.",
            ["Admin.Catalog.PriceList.Customers.SaveBeforeEdit"] = "You need to save the price list before you can add customers for this page.",
            ["Admin.Catalog.PriceList.Products.Fields.Product"] = "Product",
            ["Admin.Catalog.PriceList.Products.Fields.StandardPrice"] = "Original price",
            ["Admin.Catalog.PriceList.Products.Fields.CalculatedPrice"] = "Calculated price",
            ["Admin.Catalog.PriceList.Products.Fields.ManualPrice"] = "Manual price",

            ["Admin.Catalog.PriceList.Customers.Fields.Customer"] = "Customer",
            ["Admin.Catalog.PriceList.Products.AddNew"] = "Add product",
            ["Admin.Catalog.PriceList.Customers.AddNew"] = "Add customer",

            ["Admin.Catalog.PriceLists.Added"] = "The price list has been added successfully.",
            ["Admin.Catalog.PriceLists.Updated"] = "The price list has been updated successfully.",
            ["Admin.Catalog.PriceLists.Deleted"] = "The price list has been deleted successfully.",

            ["ActivityLog.AddNewPriceList"] = "Added a new price list. ID: {0}",
            ["ActivityLog.EditPriceList"] = "Edited a price list. ID: {0}",
            ["ActivityLog.DeletePriceList"] = "Deleted a price list. ID: {0}",

            ["Admin.Configuration.Settings.Catalog.PriceListStrategy"] = "Price list strategy",
            ["Admin.Configuration.Settings.Catalog.PriceListStrategy.Hint"] = "Select the strategy to be used when applying multiple price lists to products. The 'Minimal price' strategy applies all active price lists to products and uses the lowest calculated price. The 'Use by priority' strategy applies price lists to products in the order determined by their priority and uses the price from the first applicable price list.",
            ["Enums.Nop.Core.Domain.PriceLists.PriceListStrategy.MinimalPrice"] = "Minimal price",
            ["Enums.Nop.Core.Domain.PriceLists.PriceListStrategy.UseByPriority"] = "Use by priority",
            ["ActivityLog.ExportPriceLists"] = "{0} price lists were exported",
            ["ActivityLog.ImportPriceLists"] = "{0} price lists were imported",
            ["Admin.PriceLists.Import.ProductsDontExist"] = "Products with the following SKUs don't exist: {0}",

            ["Enums.Nop.Core.Domain.PriceLists.PriceCalculationTypeEnum.PercentageDecrease"] = "Percentage decrease",
            ["Enums.Nop.Core.Domain.PriceLists.PriceCalculationTypeEnum.PercentageIncrease"] = "Percentage increase",
            ["Enums.Nop.Core.Domain.PriceLists.PriceCalculationTypeEnum.AmountDecrease"] = "Amount decrease",
            ["Enums.Nop.Core.Domain.PriceLists.PriceCalculationTypeEnum.AmountIncrease"] = "Amount increase",
            ["Enums.Nop.Core.Domain.PriceLists.PriceCalculationTypeEnum.FixedPrice"] = "Fixed price",

            //#8161
            [$"Admin.ContentManagement.MessageTemplates.Description.{MessageTemplateSystemNames.RETURN_REQUEST_WITHDRAWAL_LINK_MESSAGE}"] = "This message template is used to send the withdrawal request confirmation.",
            ["Account.CustomerOrders.WithdrawItems"] = "Withdraw contract",
            ["Account.CustomerReturnRequests.Withdrawal.Title"] = "Withdrawal #{0} - {1}",
            ["Account.CustomerReturnRequests.Withdrawals"] = "Withdrawals",
            ["Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnWithdrawalForm"] = "Show on withdrawal form",
            ["Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnWithdrawalForm.Hint"] = "Check to show CAPTCHA on withdrawal form.",
            ["Admin.Configuration.Settings.Order.GuestReturnRequestsAllowed"] = "Allow guests to create return requests",
            ["Admin.Configuration.Settings.Order.GuestReturnRequestsAllowed.Hint"] = "Check to allow guests to create return requests.",
            ["Admin.Configuration.Settings.Order.ReturnActionsEnabled"] = "Return actions enabled",
            ["Admin.Configuration.Settings.Order.ReturnActionsEnabled.Hint"] = "Check to enable return actions.",
            ["Admin.Configuration.Settings.Order.ReturnReasonsEnabled"] = "Return reasons enabled",
            ["Admin.Configuration.Settings.Order.ReturnReasonsEnabled.Hint"] = "Check to enable return reasons.",
            ["Admin.Configuration.Settings.Order.ReturnRequestSettings"] = "Return request (withdrawal button) settings",
            ["Admin.Configuration.Settings.Order.ReturnRequestsDescription.Withdrawal"] = "The same functionality can be used to support the EU Withdrawal button (EU Directive 2023/2673).",
            ["Admin.Configuration.Settings.Order.UseEuWithdrawalLocales"] = "Locales for EU Withdrawal",
            ["Admin.Configuration.Settings.Order.UseEuWithdrawalLocales.Hint"] = "Check to use locales for the EU withdrawal button (Directive 2023/2673). Otherwise, locales for \"return requests\" will be used.",
            ["Admin.Configuration.Settings.Order.WithdrawalLinkDaysValid"] = "Withdrawal link. Days valid",
            ["Admin.Configuration.Settings.Order.WithdrawalLinkDaysValid.Hint"] = "Enter the number of days the withdrawal link remains valid. Set to 0 for no expiration.",
            ["Literals.Nop.Core.Http.NopRouteNames.General.WithdrawalRequestForm"] = "Withdraw contract",
            ["Order.WithdrawItems"] = "Withdraw contract",
            ["PageTitle.ReturnItems.Withdrawal"] = "Withdraw a contract",
            ["PageTitle.ReturnRequests.WithdrawalForm"] = "Withdraw a contract",
            ["ReturnRequests.Withdrawal.Fields.EmailAddress"] = "Email address",
            ["ReturnRequests.Withdrawal.Fields.OrderNumber"] = "Order number",
            ["ReturnRequests.Withdrawal.Submit"] = "Submit withdrawal request",
            ["ReturnRequests.Withdrawal.Submitted"] = "Your withdrawal has been submitted successfully.",
            ["ReturnRequests.Withdrawal.Title"] = "Withdraw contract for <a href=\"{0}\">order #{1}</a>",
            ["ReturnRequests.WithdrawalForm"] = "Find your order",
            ["ReturnRequests.WithdrawalForm.Submit"] = "Continue",
            ["ReturnRequests.WithdrawalForm.ConfirnationText"] = "If your details are correct, we've sent you a link to continue.",
            ["ReturnRequests.WithdrawalForm.EmailAddress.Required"] = "The Email address is required",
            ["ReturnRequests.WithdrawalForm.OrderNumber.Required"] = "The Order number is required",

            //#309
            ["Admin.Configuration.Settings.Order.NextRecurringPaymentNotificationDays"] = "Next Recurring Payment Notification Days",
            ["Admin.Configuration.Settings.Order.NextRecurringPaymentNotificationDays.Hint"] = "Number of days before the next recurring payment when customers should receive a notification email. Set to 0 to disable this notification.",

            //#8093
            ["Admin.Address.Fields.PhoneNumber.NotValid"] = "Phone number is not valid.",
            ["Admin.Customers.Customers.Fields.Phone.NotValid"] = "Phone number is not valid.",
        });

        #endregion
    }

    /// <summary>Collects the DOWN migration expressions</summary>
    public override void Down()
    {
        //add the downgrade logic if necessary 
    }
}