using FluentMigrator;
using Nop.Data;
using Nop.Data.Migrations;
using Nop.Web.Framework.Extensions;

namespace Nop.Web.Framework.Migrations.UpgradeTo500;

[NopUpdateMigration("2025-10-29 00:00:00", "5.00", UpdateMigrationType.Localization)]
public class LocalizationMigration : MigrationBase
{
    /// <summary>Collect the UP migration expressions</summary>
    public override void Up()
    {
        if (!DataSettingsManager.IsDatabaseInstalled())
            return;

        #region Delete locales

        this.DeleteLocaleResources(new List<string>
        {
            //#7340
            "ActivityLog.AddNewNews",
            "ActivityLog.DeleteNews",
            "ActivityLog.DeleteNewsComment",
            "ActivityLog.EditNews",
            "ActivityLog.EditNewsComment",
            "ActivityLog.PublicStore.AddNewsComment",
            "Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnNewsCommentPage",
            "Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnNewsCommentPage.Hint",
            "Admin.Configuration.Settings.GeneralCommon.SitemapIncludeNews",
            "Admin.Configuration.Settings.GeneralCommon.SitemapIncludeNews.Hint",
            "Admin.Configuration.Settings.News",
            "Admin.Configuration.Settings.News.AllowNotRegisteredUsersToLeaveComments",
            "Admin.Configuration.Settings.News.AllowNotRegisteredUsersToLeaveComments.Hint",
            "Admin.Configuration.Settings.News.BlockTitle.Common",
            "Admin.Configuration.Settings.News.BlockTitle.NewsComments",
            "Admin.Configuration.Settings.News.Enabled",
            "Admin.Configuration.Settings.News.Enabled.Hint",
            "Admin.Configuration.Settings.News.MainPageNewsCount",
            "Admin.Configuration.Settings.News.MainPageNewsCount.Hint",
            "Admin.Configuration.Settings.News.NewsArchivePageSize",
            "Admin.Configuration.Settings.News.NewsArchivePageSize.Hint",
            "Admin.Configuration.Settings.News.NewsCommentsMustBeApproved",
            "Admin.Configuration.Settings.News.NewsCommentsMustBeApproved.Hint",
            "Admin.Configuration.Settings.News.NotifyAboutNewNewsComments",
            "Admin.Configuration.Settings.News.NotifyAboutNewNewsComments.Hint",
            "Admin.Configuration.Settings.News.ShowHeaderRSSUrl",
            "Admin.Configuration.Settings.News.ShowHeaderRSSUrl.Hint",
            "Admin.Configuration.Settings.News.ShowNewsCommentsPerStore",
            "Admin.Configuration.Settings.News.ShowNewsCommentsPerStore.Hint",
            "Admin.Configuration.Settings.News.ShowNewsOnMainPage",
            "Admin.Configuration.Settings.News.ShowNewsOnMainPage.Hint",
            "Admin.ContentManagement.News",
            "Admin.ContentManagement.News.Comments",
            "Admin.ContentManagement.News.Comments.ApproveSelected",
            "Admin.ContentManagement.News.Comments.DeleteSelected",
            "Admin.ContentManagement.News.Comments.DisapproveSelected",
            "Admin.ContentManagement.News.Comments.Fields.CommentText",
            "Admin.ContentManagement.News.Comments.Fields.CommentTitle",
            "Admin.ContentManagement.News.Comments.Fields.CreatedOn",
            "Admin.ContentManagement.News.Comments.Fields.Customer",
            "Admin.ContentManagement.News.Comments.Fields.IsApproved",
            "Admin.ContentManagement.News.Comments.Fields.NewsItem",
            "Admin.ContentManagement.News.Comments.Fields.StoreName",
            "Admin.ContentManagement.News.Comments.List.CreatedOnFrom",
            "Admin.ContentManagement.News.Comments.List.CreatedOnFrom.Hint",
            "Admin.ContentManagement.News.Comments.List.CreatedOnTo",
            "Admin.ContentManagement.News.Comments.List.CreatedOnTo.Hint",
            "Admin.ContentManagement.News.Comments.List.SearchApproved",
            "Admin.ContentManagement.News.Comments.List.SearchApproved.All",
            "Admin.ContentManagement.News.Comments.List.SearchApproved.ApprovedOnly",
            "Admin.ContentManagement.News.Comments.List.SearchApproved.DisapprovedOnly",
            "Admin.ContentManagement.News.Comments.List.SearchApproved.Hint",
            "Admin.ContentManagement.News.Comments.List.SearchText",
            "Admin.ContentManagement.News.Comments.List.SearchText.Hint",
            "Admin.ContentManagement.News.NewsItems",
            "Admin.ContentManagement.News.NewsItems.Added",
            "Admin.ContentManagement.News.NewsItems.AddNew",
            "Admin.ContentManagement.News.NewsItems.BackToList",
            "Admin.ContentManagement.News.NewsItems.Deleted",
            "Admin.ContentManagement.News.NewsItems.EditNewsItemDetails",
            "Admin.ContentManagement.News.NewsItems.Fields.AllowComments",
            "Admin.ContentManagement.News.NewsItems.Fields.AllowComments.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Comments",
            "Admin.ContentManagement.News.NewsItems.Fields.CreatedOn",
            "Admin.ContentManagement.News.NewsItems.Fields.EndDate",
            "Admin.ContentManagement.News.NewsItems.Fields.EndDate.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Full",
            "Admin.ContentManagement.News.NewsItems.Fields.Full.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Full.Required",
            "Admin.ContentManagement.News.NewsItems.Fields.Language",
            "Admin.ContentManagement.News.NewsItems.Fields.Language.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.LimitedToStores",
            "Admin.ContentManagement.News.NewsItems.Fields.LimitedToStores.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaDescription",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaDescription.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaKeywords",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaKeywords.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaTitle",
            "Admin.ContentManagement.News.NewsItems.Fields.MetaTitle.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Published",
            "Admin.ContentManagement.News.NewsItems.Fields.Published.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.SeName",
            "Admin.ContentManagement.News.NewsItems.Fields.SeName.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Short",
            "Admin.ContentManagement.News.NewsItems.Fields.Short.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Short.Required",
            "Admin.ContentManagement.News.NewsItems.Fields.StartDate",
            "Admin.ContentManagement.News.NewsItems.Fields.StartDate.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Title",
            "Admin.ContentManagement.News.NewsItems.Fields.Title.Hint",
            "Admin.ContentManagement.News.NewsItems.Fields.Title.Required",
            "Admin.ContentManagement.News.NewsItems.Info",
            "Admin.ContentManagement.News.NewsItems.List.SearchStore",
            "Admin.ContentManagement.News.NewsItems.List.SearchStore.Hint",
            "Admin.ContentManagement.News.NewsItems.List.SearchTitle",
            "Admin.ContentManagement.News.NewsItems.List.SearchTitle.Hint",
            "Admin.ContentManagement.News.NewsItems.Updated",
            "Admin.Documentation.Reference.News",
            "News",
            "News.Comments",
            "News.Comments.CommentText",
            "News.Comments.CommentText.Required",
            "News.Comments.CommentTitle",
            "News.Comments.CommentTitle.MaxLengthValidation",
            "News.Comments.CommentTitle.Required",
            "News.Comments.CreatedOn",
            "News.Comments.LeaveYourComment",
            "News.Comments.OnlyRegisteredUsersLeaveComments",
            "News.Comments.SeeAfterApproving",
            "News.Comments.SubmitButton",
            "News.Comments.SuccessfullyAdded",
            "News.MoreInfo",
            "News.RSS",
            "News.RSS.Hint",
            "News.ViewAll",
            "PageTitle.NewsArchive",
            "Security.Permission.ContentManagement.NewsCommentsCreateEditDelete",
            "Security.Permission.ContentManagement.NewsCommentsView",
            "Security.Permission.ContentManagement.NewsCreateEditDelete",
            "Security.Permission.ContentManagement.NewsView",
            "Sitemap.News",

            //#7368
            "Admin.ContentManagement.Polls.Polls",
            "Admin.ContentManagement.Polls.Added",
            "Admin.ContentManagement.Polls.AddNew",
            "Admin.ContentManagement.Polls.Answers",
            "Admin.ContentManagement.Polls.Answers.Fields.DisplayOrder",
            "Admin.ContentManagement.Polls.Answers.Fields.DisplayOrder.Hint",
            "Admin.ContentManagement.Polls.Answers.Fields.Name",
            "Admin.ContentManagement.Polls.Answers.Fields.Name.Hint",
            "Admin.ContentManagement.Polls.Answers.Fields.Name.Required",
            "Admin.ContentManagement.Polls.Answers.Fields.NumberOfVotes",
            "Admin.ContentManagement.Polls.Answers.SaveBeforeEdit",
            "Admin.ContentManagement.Polls.BackToList",
            "Admin.ContentManagement.Polls.Configuration.Enabled",
            "Admin.ContentManagement.Polls.Configuration.Enabled.Hint",
            "Admin.ContentManagement.Polls.Deleted",
            "Admin.ContentManagement.Polls.EditPollDetails",
            "Admin.ContentManagement.Polls.Fields.AllowGuestsToVote",
            "Admin.ContentManagement.Polls.Fields.AllowGuestsToVote.Hint",
            "Admin.ContentManagement.Polls.Fields.DisplayOrder",
            "Admin.ContentManagement.Polls.Fields.DisplayOrder.Hint",
            "Admin.ContentManagement.Polls.Fields.EndDate",
            "Admin.ContentManagement.Polls.Fields.EndDate.Hint",
            "Admin.ContentManagement.Polls.Fields.Language",
            "Admin.ContentManagement.Polls.Fields.Language.Hint",
            "Admin.ContentManagement.Polls.Fields.LimitedToStores",
            "Admin.ContentManagement.Polls.Fields.LimitedToStores.Hint",
            "Admin.ContentManagement.Polls.Fields.Name",
            "Admin.ContentManagement.Polls.Fields.Name.Hint",
            "Admin.ContentManagement.Polls.Fields.Name.Required",
            "Admin.ContentManagement.Polls.Fields.Published",
            "Admin.ContentManagement.Polls.Fields.Published.Hint",
            "Admin.ContentManagement.Polls.Fields.ShowOnHomepage",
            "Admin.ContentManagement.Polls.Fields.ShowOnHomepage.Hint",
            "Admin.ContentManagement.Polls.Fields.ShowInLeftSideColumn",
            "Admin.ContentManagement.Polls.Fields.ShowInLeftSideColumn.Hint",
            "Admin.ContentManagement.Polls.Fields.StartDate",
            "Admin.ContentManagement.Polls.Fields.StartDate.Hint",
            "Admin.ContentManagement.Polls.Info",
            "Admin.ContentManagement.Polls.List.SearchStore",
            "Admin.ContentManagement.Polls.List.SearchStore.Hint",
            "Admin.ContentManagement.Polls.Updated",
            "Admin.Documentation.Reference.Polls",
            "Polls.OnlyRegisteredUsersVote",
            "Polls.SelectAnswer",
            "Polls.Title",
            "Polls.TotalVotes",
            "Polls.Vote",
            "Polls.VotesResultLine",
            "Security.Permission.ContentManagement.PollsCreateEditDelete",
            "Security.Permission.ContentManagement.PollsView",
            "Account.ForumSubscriptions",
            "Account.ForumSubscriptions.DeleteSelected",
            "Account.ForumSubscriptions.Description",
            "Account.ForumSubscriptions.InfoColumn",
            "Account.ForumSubscriptions.NoSubscriptions",

            //#7336
            "Admin.Configuration.Settings.Forums",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsFeedCount",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsFeedCount.Hint",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsFeedEnabled",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsFeedEnabled.Hint",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsPageSize",
            "Admin.Configuration.Settings.Forums.ActiveDiscussionsPageSize.Hint",
            "Admin.Configuration.Settings.Forums.AllowCustomersToDeletePosts",
            "Admin.Configuration.Settings.Forums.AllowCustomersToDeletePosts.Hint",
            "Admin.Configuration.Settings.Forums.AllowCustomersToEditPosts",
            "Admin.Configuration.Settings.Forums.AllowCustomersToEditPosts.Hint",
            "Admin.Configuration.Settings.Forums.AllowCustomersToManageSubscriptions",
            "Admin.Configuration.Settings.Forums.AllowCustomersToManageSubscriptions.Hint",
            "Admin.Configuration.Settings.Forums.AllowGuestsToCreatePosts",
            "Admin.Configuration.Settings.Forums.AllowGuestsToCreatePosts.Hint",
            "Admin.Configuration.Settings.Forums.AllowGuestsToCreateTopics",
            "Admin.Configuration.Settings.Forums.AllowGuestsToCreateTopics.Hint",
            "Admin.Configuration.Settings.Forums.AllowPostVoting",
            "Admin.Configuration.Settings.Forums.AllowPostVoting.Hint",
            "Admin.Configuration.Settings.Forums.BlockTitle.Common",
            "Admin.Configuration.Settings.Forums.BlockTitle.Feeds",
            "Admin.Configuration.Settings.Forums.BlockTitle.PageSizes",
            "Admin.Configuration.Settings.Forums.BlockTitle.Permissions",
            "Admin.Configuration.Settings.Forums.ForumEditor",
            "Admin.Configuration.Settings.Forums.ForumEditor.Hint",
            "Admin.Configuration.Settings.Forums.ForumFeedCount",
            "Admin.Configuration.Settings.Forums.ForumFeedCount.Hint",
            "Admin.Configuration.Settings.Forums.ForumFeedsEnabled",
            "Admin.Configuration.Settings.Forums.ForumFeedsEnabled.Hint",
            "Admin.Configuration.Settings.Forums.ForumsEnabled",
            "Admin.Configuration.Settings.Forums.ForumsEnabled.Hint",
            "Admin.Configuration.Settings.Forums.MaxVotesPerDay",
            "Admin.Configuration.Settings.Forums.MaxVotesPerDay.Hint",
            "Admin.Configuration.Settings.Forums.PostsPageSize",
            "Admin.Configuration.Settings.Forums.PostsPageSize.Hint",
            "Admin.Configuration.Settings.Forums.RelativeDateTimeFormattingEnabled",
            "Admin.Configuration.Settings.Forums.RelativeDateTimeFormattingEnabled.Hint",
            "Admin.Configuration.Settings.Forums.SearchResultsPageSize",
            "Admin.Configuration.Settings.Forums.SearchResultsPageSize.Hint",
            "Admin.Configuration.Settings.Forums.ShowCustomersPostCount",
            "Admin.Configuration.Settings.Forums.ShowCustomersPostCount.Hint",
            "Admin.Configuration.Settings.Forums.SignaturesEnabled",
            "Admin.Configuration.Settings.Forums.SignaturesEnabled.Hint",
            "Admin.Configuration.Settings.Forums.TopicsPageSize",
            "Admin.Configuration.Settings.Forums.TopicsPageSize.Hint",
            "Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnForum",
            "Admin.Configuration.Settings.GeneralCommon.CaptchaShowOnForum.Hint",
            "Admin.ContentManagement.Forums",
            "Admin.ContentManagement.Forums.Forum",
            "Admin.ContentManagement.Forums.Forum.Added",
            "Admin.ContentManagement.Forums.Forum.BackToList",
            "Admin.ContentManagement.Forums.Forum.CreateForum",
            "Admin.ContentManagement.Forums.Forum.Deleted",
            "Admin.ContentManagement.Forums.Forum.EditForum",
            "Admin.ContentManagement.Forums.Forum.Fields.CreatedOn",
            "Admin.ContentManagement.Forums.Forum.Fields.Description",
            "Admin.ContentManagement.Forums.Forum.Fields.Description.Hint",
            "Admin.ContentManagement.Forums.Forum.Fields.DisplayOrder",
            "Admin.ContentManagement.Forums.Forum.Fields.DisplayOrder.Hint",
            "Admin.ContentManagement.Forums.Forum.Fields.ForumGroupId",
            "Admin.ContentManagement.Forums.Forum.Fields.ForumGroupId.Hint",
            "Admin.ContentManagement.Forums.Forum.Fields.ForumGroupId.Required",
            "Admin.ContentManagement.Forums.Forum.Fields.Name",
            "Admin.ContentManagement.Forums.Forum.Fields.Name.Hint",
            "Admin.ContentManagement.Forums.Forum.Fields.Name.Required",
            "Admin.ContentManagement.Forums.Forum.Updated",
            "Admin.ContentManagement.Forums.ForumGroup",
            "Admin.ContentManagement.Forums.ForumGroup.Added",
            "Admin.ContentManagement.Forums.ForumGroup.BackToList",
            "Admin.ContentManagement.Forums.ForumGroup.CreateForumGroup",
            "Admin.ContentManagement.Forums.ForumGroup.Deleted",
            "Admin.ContentManagement.Forums.ForumGroup.EditForumGroup",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.CreatedOn",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.DisplayOrder",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.DisplayOrder.Hint",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.Name",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.Name.Hint",
            "Admin.ContentManagement.Forums.ForumGroup.Fields.Name.Required",
            "Admin.ContentManagement.Forums.ForumGroup.Updated",

            "Admin.Documentation.Reference.Forums",

            "Enums.Nop.Core.Domain.Forums.EditorType.BBCodeEditor",
            "Enums.Nop.Core.Domain.Forums.EditorType.HtmlEditor",
            "Enums.Nop.Core.Domain.Forums.EditorType.MarkdownEditor",
            "Enums.Nop.Core.Domain.Forums.EditorType.SimpleTextBox",
            "Enums.Nop.Core.Domain.Forums.ForumSearchType.All",
            "Enums.Nop.Core.Domain.Forums.ForumSearchType.PostTextOnly",
            "Enums.Nop.Core.Domain.Forums.ForumSearchType.TopicTitlesOnly",
            "Enums.Nop.Core.Domain.Forums.ForumTopicType.Announcement",
            "Enums.Nop.Core.Domain.Forums.ForumTopicType.Normal",
            "Enums.Nop.Core.Domain.Forums.ForumTopicType.Sticky",

            "Forum.ActiveDiscussions",
            "Forum.ActiveDiscussions.ViewAll",
            "Forum.ActiveDiscussionsFeedDescription",
            "Forum.ActiveDiscussionsFeedTitle",
            "Forum.ActiveDiscussionsRSSLinkTitle",
            "Forum.AdvancedSearch",
            "Forum.Announcement",
            "Forum.Author",
            "Forum.Breadcrumb.ForumGroupTitle",
            "Forum.Breadcrumb.ForumHomeTitle",
            "Forum.Breadcrumb.ForumTitle",
            "Forum.Breadcrumb.HomeTitle",
            "Forum.Breadcrumb.TopicTitle",
            "Forum.By",
            "Forum.Cancel",
            "Forum.DeletePost",
            "Forum.DeleteTopic",
            "Forum.EditPost",
            "Forum.EditTopic",
            "Forum.Forum",
            "Forum.ForumFeedDescription",
            "Forum.ForumFeedTitle",
            "Forum.ForumName",
            "Forum.ForumRSSLinkTitle",
            "Forum.Forums",
            "Forum.Home",
            "Forum.In",
            "Forum.Joined",
            "Forum.LatestPost",
            "Forum.Location",
            "Forum.Moderator",
            "Forum.MoveTopic",
            "Forum.NewPost",
            "Forum.NewTopic",
            "Forum.NoPosts",
            "Forum.Normal",
            "Forum.NotifyWhenSomeonePostsInThisTopic",
            "Forum.PageTitle.ActiveDiscussions",
            "Forum.PageTitle.Default",
            "Forum.PageTitle.MoveTopic",
            "Forum.PageTitle.PostEdit",
            "Forum.PageTitle.PostNew",
            "Forum.PageTitle.Search",
            "Forum.PageTitle.TopicEdit",
            "Forum.PageTitle.TopicNew",
            "Forum.Post.IsNotUseful",
            "Forum.Post.IsUseful",
            "Forum.Post.Text",
            "Forum.Posted",
            "Forum.PostLinkTitle",
            "Forum.Posts",
            "Forum.Priority",
            "Forum.PrivateMessages.PM",
            "Forum.QuotePost",
            "Forum.Replies",
            "Forum.Reply",
            "Forum.RSS",
            "Forum.Search",
            "Forum.Search.AdvancedSearch",
            "Forum.Search.LimitResultsToPrevious",
            "Forum.Search.LimitResultsToPrevious.1day",
            "Forum.Search.LimitResultsToPrevious.1month",
            "Forum.Search.LimitResultsToPrevious.1year",
            "Forum.Search.LimitResultsToPrevious.2weeks",
            "Forum.Search.LimitResultsToPrevious.3months",
            "Forum.Search.LimitResultsToPrevious.6months",
            "Forum.Search.LimitResultsToPrevious.7days",
            "Forum.Search.LimitResultsToPrevious.AllResults",
            "Forum.Search.SearchInForum",
            "Forum.Search.SearchInForum.All",
            "Forum.Search.SearchKeyword",
            "Forum.Search.SearchWithin",
            "Forum.Search.SearchWithin.All",
            "Forum.Search.SearchWithin.PostTextOnly",
            "Forum.Search.SearchWithin.TopicTitlesOnly",
            "Forum.SearchButton",
            "Forum.SearchForumsTooltip",
            "Forum.SearchNoResultsText",
            "Forum.SearchTermMinimumLengthIsNCharacters",
            "Forum.SelectTheForumToMoveTopic",
            "Forum.Status",
            "Forum.Sticky",
            "Forum.Submit",
            "Forum.TextCannotBeEmpty",
            "Forum.Topics",
            "Forum.Topics.GotoPostPager",
            "Forum.TopicSubjectCannotBeEmpty",
            "Forum.TopicTitle",
            "Forum.TruncatePostfix",
            "Forum.TotalPosts",
            "Forum.UnwatchForum",
            "Forum.UnwatchTopic",
            "Forum.Views",
            "Forum.Votes",
            "Forum.Votes.AlreadyVoted",
            "Forum.Votes.Login",
            "Forum.Votes.MaxVotesReached",
            "Forum.Votes.OwnPost",
            "Forum.WatchForum",
            "Forum.WatchTopic",

            "MarkdownEditor.TabWrite",
            "MarkdownEditor.TabPreview",

            "Literals.Nop.Core.Http.NopRouteNames.General.Boards",
            "PageTitle.ForumSubscriptions",

            "Security.Permission.ContentManagement.ForumsCreateEditDelete",
            "Security.Permission.ContentManagement.ForumsView",

            "Profile.LatestPosts",
            "Profile.LatestPosts.NoPosts",
            "Profile.PersonalInfo",            
        });

        #endregion

        #region Rename locales

        this.RenameLocales(new Dictionary<string, string>
        {
            ["Admin.Configuration.Settings.Forums.AllowPrivateMessages"] = "Admin.Configuration.Settings.CustomerUser.AllowPrivateMessages",
            ["Admin.Configuration.Settings.Forums.AllowPrivateMessages.Hint"] = "Admin.Configuration.Settings.CustomerUser.AllowPrivateMessages.Hint",
            ["Admin.Configuration.Settings.Forums.ShowAlertForPM"] = "Admin.Configuration.Settings.CustomerUser.ShowAlertForPM",
            ["Admin.Configuration.Settings.Forums.ShowAlertForPM.Hint"] = "Admin.Configuration.Settings.CustomerUser.ShowAlertForPM.Hint",
            ["Admin.Configuration.Settings.Forums.NotifyAboutPrivateMessages"] = "Admin.Configuration.Settings.CustomerUser.NotifyAboutPrivateMessages",
            ["Admin.Configuration.Settings.Forums.NotifyAboutPrivateMessages.Hint"] = "Admin.Configuration.Settings.CustomerUser.NotifyAboutPrivateMessages.Hint",

            //#8097
            ["Admin.Configuration.Settings.GeneralCommon.TwitterLink"] = "Admin.Configuration.Settings.GeneralCommon.XLink",
            ["Admin.Configuration.Settings.GeneralCommon.TwitterLink.Hint"] = "Admin.Configuration.Settings.GeneralCommon.XLink.Hint",
            ["Footer.FollowUs.Twitter"] = "Footer.FollowUs.X",
        });

        #endregion

        #region Add or update locales

        this.AddOrUpdateLocaleResource(new Dictionary<string, string>
        {
            //#7898
            ["Admin.Configuration.Settings.Catalog.ArtificialIntelligence.LogRequests"] = "Log AI requests",
            ["Admin.Configuration.Settings.Catalog.ArtificialIntelligence.LogRequests.Hint"] = "Check to enable logging of all requests to AI services.",

            //#7989
            ["Products.ProductHasBeenUpdatedInTheWishlist.Link"] = "The product has been updated in your <a href=\"{0}\">wishlist</a>",
            
            //#8021
            ["Admin.Catalog.Products.RelatedProducts.CyclicallyRelated"] = "Circular dependency is not allowed for required products (e.g. product A requires product B. And product B requires product A)",

            //#7906
            ["Wishlist.DuplicateName"] = "A wishlist with this name already exists.",

            //#7907
            ["Wishlist.RenameCustomWishlist"] = "Rename wishlist",

            //#7336
            ["Admin.ContentManagement.MessageTemplates.Description.Customer.NewPM"] = "This message template is used when the customer gets a notification about a new private message being received. You can set up this option by ticking the checkbox <strong>Show alert for PM</strong> in Configuration - Settings - Customer settings.",
            ["Admin.Configuration.Settings.CustomerUser.BlockTitle.PrivateMessage"] = "Private messages",

            //#8125
            ["Admin.Configuration.Settings.Catalog.ShowCategoryProductNumber"] = "Show the number of products next to each category",
            ["Admin.Configuration.Settings.Catalog.ShowCategoryProductNumber.Hint"] = "Check to show the number of products next to each category (category navigation block).",
            ["Admin.Configuration.Settings.Catalog.ShowCategoryProductNumberIncludingSubcategories"] = "Include subcategories (number of products)",
            ["Admin.Configuration.Settings.Catalog.ShowCategoryProductNumberIncludingSubcategories.Hint"] = "Check to include subcategories when showing the number of products next to each category.",

            //#7386
            ["Admin.Configuration.Settings.Shipping.AllowCustomerToChooseDeliveryDate"] = "Allow customers to choose delivery date",
            ["Admin.Configuration.Settings.Shipping.AllowCustomerToChooseDeliveryDate.Hint"] = "Enables customers to select their preferred delivery date during checkout. This option is available only when the selected shipping method has a defined TransitDays value.",
            ["Admin.Configuration.Settings.Shipping.DeliveryDateRangeDays"] = "Range of days to choose from",
            ["Admin.Configuration.Settings.Shipping.DeliveryDateRangeDays.Hint"] = "Specifies how many delivery date options will be available to customers, starting from the earliest possible delivery date calculated using TransitDays.",
            ["Checkout.SelectDesiredDeliveryDate"] = "Select desired delivery date",
            ["Admin.Orders.Fields.DesiredDeliveryDate"] = "Desired delivery date",
            ["Admin.Orders.Fields.DesiredDeliveryDate.Hint"] = "The delivery date selected by the customer during checkout.",
            ["Order.Shipping.DesiredDeliveryDate"] = "Desired delivery date",

            //#8097
            ["Admin.Configuration.Settings.GeneralCommon.XLink"] = "X page URL",
            ["Admin.Configuration.Settings.GeneralCommon.XLink.Hint"] = "Specify your X page URL. Leave empty if you have no such page.",
            ["Footer.FollowUs.X"] = "X",

            //#8073
            ["Admin.System.SystemInfo.NopLatestVersion"] = "Latest nopCommerce version",
            ["Admin.System.SystemInfo.NopLatestVersion.Hint"] = "The latest nopCommerce version, available for download.",
            ["Admin.System.SystemInfo.NopLatestVersion.Text"] = "<a href='{1}' target='_blank'>{0}</a> (see the <a href='{2}' target='_blank'>release-notes</a>)",

            //#8136
            ["Footer.FollowUs.TikTok"] = "TikTok",
            ["Footer.FollowUs.Snapchat"] = "Snapchat",
            ["Footer.FollowUs.Pinterest"] = "Pinterest",
            ["Footer.FollowUs.Tumblr"] = "Tumblr",
            ["Admin.Configuration.Settings.GeneralCommon.TikTokLink"] = "TikTok URL",
            ["Admin.Configuration.Settings.GeneralCommon.TikTokLink.Hint"] = "Specify your TikTok page URL. Leave empty if you have no such page.",
            ["Admin.Configuration.Settings.GeneralCommon.SnapchatLink"] = "Snapchat URL",
            ["Admin.Configuration.Settings.GeneralCommon.SnapchatLink.Hint"] = "Specify your Snapchat page URL. Leave empty if you have no such page.",
            ["Admin.Configuration.Settings.GeneralCommon.PinterestLink"] = "Pinterest URL",
            ["Admin.Configuration.Settings.GeneralCommon.PinterestLink.Hint"] = "Specify your Pinterest page URL. Leave empty if you have no such page.",
            ["Admin.Configuration.Settings.GeneralCommon.TumblrLink"] = "Tumblr URL",
            ["Admin.Configuration.Settings.GeneralCommon.TumblrLink.Hint"] = "Specify your Tumblr page URL. Leave empty if you have no such page.",
        });

        #endregion
    }

    /// <summary>Collects the DOWN migration expressions</summary>
    public override void Down()
    {
        //add the downgrade logic if necessary 
    }
}