---
name: "dotnetcore"
on:
  push:
    branches:
       - main
jobs:
   build:
      name: build
      runs-on: "ubuntu-24.04"
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-dotnet@v4   
          with:                                        
           dotnet-version: "9.0.100"
        - name: restore
          run: dotnet restore  src/Presentation/Nop.Web/Nop.Web.csproj
        - name: build
          run: dotnet build  src/Presentation/Nop.Web/Nop.Web.csproj --configuration Debug
        
        - name: Build and analyze
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: |
             dotnet sonarscanner begin /k:"mohitingole_nopCommerce" /o:"mohitingole" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
             dotnet build src/Presentation/Nop.Web/Nop.Web.csproj
             dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"