---
name: "dotnetcore"
on:
  push:
    branches:
       - develop
jobs:
   build:
      name: build
      runs-on: 'dotnet9'
      steps:
        - uses: actions/checkout@v4
        - name: build
          run: dotnet build  src/Presentation/Nop.Web/Nop.Web.csproj --configuration Debug