name: Build and Test

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Restore dependencies
        run: dotnet restore src/Presentation/Nop.Web/Nop.Web.csproj

      - name: Build
        run: dotnet build --configuration Debug src/Presentation/Nop.Web/Nop.Web.csproj --no-restore

      - name: Run tests
        run: dotnet test src/Tests/Nop.Tests/Nop.Tests.csproj

      - name: Publish
        run: dotnet publish --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj --output published
